<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'EN US', 'English', 'English', array (
		// Dictionary entries go here
		'Menu:Monitoring' => 'Monitoring',
		'Server:options' => 'Options',
		'Class:BaseMonitoring' => 'Monitoring Based',
		'Class:BaseMonitoring/Name' => '%1$s - %2$s',
		'Class:BaseMonitoring/Attribute:name' => 'Name',
		'Class:BaseMonitoring/Attribute:name+' => 'Warning, name is used to find iTop\'s CI to link it in the ticket in case of alart',
		'Class:BaseMonitoring/Attribute:org_id' => 'Organisation',
		'Class:BaseMonitoring/Attribute:organization_uniq_id' => 'Organization Uniq ID',
		'Class:BaseMonitoring/Attribute:functionalci_id' => 'CI',
		'Class:BaseMonitoring/Attribute:functionalci_id+' => 'CI using this monitoring',
		'Class:BaseMonitoring/Attribute:monitoring_box_id' => 'Monitoring box',
		'Class:BaseMonitoring/Attribute:monitoring_box_id+' => 'You can force monitoring box',
		'Class:BaseMonitoring/Attribute:monitoring_id' => 'Monitoring\'s id',
		'Class:BaseMonitoring/Attribute:monitoring_id+' => 'Cross reference between monitoring tools and CMDB',
		'Class:BaseMonitoring/Attribute:etiquettes' => 'Suplementary tags',
		'Class:BaseMonitoring/Attribute:etiquettes+' => 'Non standard tags to add',
		'Class:BaseMonitoring/Attribute:monitoring_url' => 'Monitoring URL',
		'Class:BaseMonitoring/Attribute:monitoring_url+' => 'URL of equipment in monitoring tool',
		
		'Class:BaseMonitoring/Attribute:monitoring_box_id' => 'Boitier de supervision',
		'Class:BaseMonitoring/Attribute:monitoring_box_id+' => 'Permet de forcer un boitier de supervision',
		'Class:BaseMonitoring/Attribute:monitoring_id' => 'Id dans l\'outil de supervision',
		'Class:BaseMonitoring/Attribute:monitoring_id+' => 'Cross référence entre la supervision et la CMDB',
		'Class:BaseMonitoring/Attribute:etiquettes' => 'Etiquettes supplémentaires',
		'Class:BaseMonitoring/Attribute:etiquettes+' => 'Etiquettes non standard à ajouter à la supervision',
		'Class:BaseMonitoring/Attribute:category' => 'Catégorie de supervision',
		'Class:BaseMonitoring/Attribute:category+' => 'Catégorie utilisée par cette supervision',
		'Class:BaseMonitoring/Attribute:modele_id' => 'Modèle de supervision',
		'Class:BaseMonitoring/Attribute:modele_id+' => 'Modèle de service utilisé par cette supervision',
		
		'Class:ControlMonitoring/Name' => '%1$s - %2$s',
		'Class:ControlMonitoring' => 'VM control for Monitoring',
		'Class:ControlMonitoring/Attribute:controle_id' => 'Control template',
		'Class:ControlMonitoring/Attribute:controle_id+' => 'Template of control if equipment is alive',
		'Class:ControlMonitoring/Attribute:seuil_control_alerte' => 'Warning threshold (ms)',
		'Class:ControlMonitoring/Attribute:seuil_control_critique' => 'Error threshold (ms)',
		'ControlMonitoring:control' => 'Used For Alive Control',
		
		'Class:AppsMonitoring/Name' => '%1$s - %2$s',
		'Class:AppsMonitoring' => 'Applicative Service\'s Monitoring',
		'Class:AppsMonitoring/Attribute:monitoring_apps_standard_account' => 'Use standard account ?',
		'Class:AppsMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Yes',
		'Class:AppsMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'No',
		'Class:AppsMonitoring/Attribute:service_params' => 'Template\s parameters list',
		'Class:AppsMonitoring/Attribute:service_params+' => 'Template\s parameters list must have 1 per line and follows this format : nom::valeur',
		'Class:AppsMonitoring/Attribute:monitoring_host_id' => 'Apps\'s equipment',
		'Class:AppsMonitoring/Attribute:monitoring_host_id+' => 'Define which equiment receive this monitoring service',
		'AppsMonitoring:modele' => 'Monitoring template',
		
		'Class:FacilitiesMonitoring/Name' => '%1$s - %2$s',
		'Class:FacilitiesMonitoring' => 'Facilities Monitoring',
		'Class:FacilitiesMonitoring/Attribute:monitoring_apps_standard_account' => 'Use standard account ?',
		'Class:FacilitiesMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Yes',
		'Class:FacilitiesMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'No',
		'Class:FacilitiesMonitoring/Attribute:monitoring_host_snmp' => 'Template based on SNMP ?',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect' => 'Enable  electrical collect ?',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect+' => 'Based on CI, retrieves PDUs linked to CI to add electrical collect',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect/Value:yes' => 'Yes',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect/Value:no' => 'No',
		'Class:FacilitiesMonitoring/Attribute:modele_collect_id' => 'Electrical collect template',
		'Class:FacilitiesMonitoring/Attribute:appsmonitoring_list' => 'Applicative Monitoring',
		'FacilitiesMonitoring:modelehost' => 'Monitoring template',
		'FacilitiesMonitoring:collectelect' => 'Collecte électrique',
		
		'Class:NetworkMonitoring/Name' => '%1$s - %2$s',
		'Class:NetworkMonitoring' => 'Network Monitoring',
		'Class:NetworkMonitoring/Attribute:monitoring_apps_standard_account' => 'Use standard account ?',
		'Class:NetworkMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Yes',
		'Class:NetworkMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'No',
		'Class:NetworkMonitoring/Attribute:monitoring_host_snmp' => 'Template based on SNMP ?',
		'Class:NetworkMonitoring/Attribute:monitoring_host_ssh' => 'Template based on SSH ?',
		'Class:NetworkMonitoring/Attribute:appsmonitoring_list' => 'Applicative Monitoring',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools' => 'Monitoring tools',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools+' => 'Monitoring tools contains this CI',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools/Value:evobserv' => 'EV Observ',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools/Value:librenms' => 'Libre NMS',
		'NetworkMonitoring:modelehost' => 'Modèle de supervision',
		
		'Class:OSMonitoring/Name' => '%1$s - %2$s',
		'Class:OSMonitoring' => 'Monitoring Via OS',
		'Class:OSMonitoring/Attribute:monitoring_apps_standard_account' => 'Use standard account ?',
		'Class:OSMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Yes',
		'Class:OSMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'No',
		'Class:OSMonitoring/Attribute:monitoring_host_snmp' => 'Template based on SNMP ?',
		'Class:OSMonitoring/Attribute:monitoring_host_wmi' => 'Template based on WMI ?',
		'Class:OSMonitoring/Attribute:monitoring_host_ssh' => 'Template based on SSH ?',
		'Class:OSMonitoring/Attribute:monitoring_host_api' => 'Template based on API ?',
		'Class:OSMonitoring/Attribute:appsmonitoring_list' => 'Applicative Monitoring',
		'OSMonitoring:modelehost' => 'Monitoring template',
		
		'Class:ServerMonitoring/Name' => '%1$s - %2$s',
		'Class:ServerMonitoring' => 'Out-Of-Band Monitoring  ilo/idrac/ipmi',
		'Class:ServerMonitoring/Attribute:monitoring_apps_standard_account' => 'Use standard account ?',
		'Class:ServerMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Yes',
		'Class:ServerMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'No',
		'Class:ServerMonitoring/Attribute:monitoring_host_snmp' => 'Template based on SNMP ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_idrac' => 'Template based on Idrac ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_ssh' => 'Template based on SSH ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_ipmi' => 'Template based on IPMI ?',
		'Class:ServerMonitoring/Attribute:appsmonitoring_list' => 'Applicative Monitoring',
		'ServerMonitoring:modelehost' => 'Monitoring template',
		
		'Class:VMMonitoring/Name' => '%1$s - %2$s',
		'Class:VMMonitoring' => 'Monitoring Via ESX/VCenter',
		'Class:VMMonitoring/Attribute:modele_id' => 'Modèle de supervision par vcenter',
		'Class:VMMonitoring/Attribute:modele_id+' => 'Modèle d\'équipement utilisé par cette supervision par Vcenter',
		'Class:VMMonitoring/Attribute:monitoring_apps_standard_account' => 'Use standard account ?',
		'Class:VMMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Yes',
		'Class:VMMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'No',
		'Class:VMMonitoring/Attribute:vcenter_id' => 'Nom du vcenter',
		'Class:VMMonitoring/Attribute:vcenter_id+' => 'Permet de définir l\'url du Vcenter à contacter.',
		'Class:VMMonitoring/Attribute:modele_vmwaretools_id' => 'Modèle de service de type VMWareTools',
		'Class:VMMonitoring/Attribute:modele_vmwaretools_id+' => 'Permet d\'ajouter les VMWare Tools en supervision',
		'Class:VMMonitoring/Attribute:appsmonitoring_list' => 'Applicative Monitoring',
		'VMMonitoring:modelevirtu' => 'Monitoring template via VCenter',
		
		'Class:FunctionalCI/Attribute:monitoring_list' => 'Monitoring list',
		'Class:FunctionalCI/Attribute:monitoring_list+' => 'Monitoring used by this CI',
		'Class:FunctionalCI/Attribute:needmonitoring' => 'Monitored ?',
		'Class:FunctionalCI/Attribute:needmonitoring+' => 'This CI must be Monitored ?',
		'Class:FunctionalCI/Attribute:needmonitoring/Value:yes' => 'Oui',
		'Class:FunctionalCI/Attribute:needmonitoring/Value:no' => 'Non',
		'Class:MonitoringModele' => 'Monitoring Template',
		'Class:MonitoringModele/Attribute:monitorings_list' => 'Monitoring list',
		'Class:MonitoringModele/Attribute:monitorings_list+' => 'Monitoring using this template',
		'Class:MonitoringModele/Attribute:controls_list' => 'Control list',
		'Class:MonitoringModele/Attribute:controls_list+' => 'Control using this template',
		'Class:MonitoringModele/Attribute:modeletype' => 'Template Type',
		'Class:MonitoringModele/Attribute:modeletype/Value:equipment' => 'Equipment',
		'Class:MonitoringModele/Attribute:modeletype/Value:service' => 'Service',
		'Class:MonitoringModele/Attribute:modeletype/Value:controle' => 'Control',
		'CI:Overview:Monitoring' => 'Monitoring list',
		'CI:Overview:Monitoring:subtitle' => 'Monitoring used by this CI',
		'BaseMonitoring:baseinfo' => 'General information',
		'BaseMonitoring:modele' => 'Equipment Template',
		'VMMonitoring:control' => 'Control Equipment Template',
) );
?>
