<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'FR FR', 'French', 'Français', array (
		// Dictionary entries go here
		'Menu:Monitoring' => 'Monitoring',
		'Server:options' => 'Options',
		'Class:BaseMonitoring' => 'Base de supervision',
		'Class:BaseMonitoring/Name' => '%1$s - %2$s',
		'Class:BaseMonitoring/Attribute:name' => 'Nom',
		'Class:BaseMonitoring/Attribute:name+' => 'Attention, le nom sert a retrouver le CI dans iTop pour le lier au ticket en cas d\'alerte',
		'Class:BaseMonitoring/Attribute:org_id' => 'Organisation',
		'Class:BaseMonitoring/Attribute:organization_uniq_id' => 'ID unique de l\'organisation',
		'Class:BaseMonitoring/Attribute:functionalci_id' => 'CI',
		'Class:BaseMonitoring/Attribute:functionalci_id+' => 'CI utilisant cette supervision',
		'Class:BaseMonitoring/Attribute:monitoring_box_id' => 'Boitier de supervision',
		'Class:BaseMonitoring/Attribute:monitoring_box_id+' => 'Permet de forcer un boitier de supervision',
		'Class:BaseMonitoring/Attribute:monitoring_id' => 'Id dans l\'outil de supervision',
		'Class:BaseMonitoring/Attribute:monitoring_id+' => 'Cross référence entre la supervision et la CMDB',
		'Class:BaseMonitoring/Attribute:etiquettes' => 'Etiquettes supplémentaires',
		'Class:BaseMonitoring/Attribute:etiquettes+' => 'Etiquettes non standard à ajouter à la supervision',
		'Class:BaseMonitoring/Attribute:category' => 'Catégorie de supervision',
		'Class:BaseMonitoring/Attribute:category+' => 'Catégorie utilisée par cette supervision',
		'Class:BaseMonitoring/Attribute:modele_id' => 'Modèle de supervision',
		'Class:BaseMonitoring/Attribute:modele_id+' => 'Modèle de service utilisé par cette supervision',
		'Class:BaseMonitoring/Attribute:monitoring_url' => 'URL de monitoring',
		'Class:BaseMonitoring/Attribute:monitoring_url+' => 'URL du composant dans l\'outil de monitoring',
		
		'Class:ControlMonitoring/Name' => '%1$s - %2$s',
		'Class:ControlMonitoring' => 'Contrôle de VM pour la Supervision',
		'Class:ControlMonitoring/Attribute:controle_id' => 'Modèle de contrôle de l\'équipement',
		'Class:ControlMonitoring/Attribute:controle_id+' => 'Modèle utilisé pour le contrôle de présence de l\'équipement',
		'Class:ControlMonitoring/Attribute:seuil_control_alerte' => 'Seuil d\'alerte/warning (ms)',
		'Class:ControlMonitoring/Attribute:seuil_control_critique' => 'Seuil critique/erreur (ms)',
		'ControlMonitoring:control' => 'Utilisé pour contrôler la présence',
		
		'Class:AppsMonitoring/Name' => '%1$s - %2$s',
		'Class:AppsMonitoring' => 'Supervision services applicatifs',
		'Class:AppsMonitoring/Attribute:monitoring_apps_standard_account' => 'Utiliser le compte standard ?',
		'Class:AppsMonitoring/Attribute:monitoring_apps_standard_account/Value:yes' => 'Oui',
		'Class:AppsMonitoring/Attribute:monitoring_apps_standard_account/Value:no' => 'Non',
		'Class:AppsMonitoring/Attribute:service_params' => 'Liste des paramètres du modèle',
		'Class:AppsMonitoring/Attribute:service_params+' => 'Les paramètres doivent être 1 par ligne et au format : nom::valeur',
		'Class:AppsMonitoring/Attribute:monitoring_host_id' => 'Equipement recevant l\'application',
		'Class:AppsMonitoring/Attribute:monitoring_host_id+' => 'Définit sur quel équipement le service applicatif doit être déployé',
		'AppsMonitoring:modele' => 'Modèle de supervision',
		
		'Class:FacilitiesMonitoring/Name' => '%1$s - %2$s',
		'Class:FacilitiesMonitoring' => 'Supervision ElectroMéchanique',
		'Class:FacilitiesMonitoring/Attribute:monitoring_host_standard_account' => 'Utiliser le compte standard ?',
		'Class:FacilitiesMonitoring/Attribute:monitoring_host_standard_account/Value:yes' => 'Oui',
		'Class:FacilitiesMonitoring/Attribute:monitoring_host_standard_account/Value:no' => 'Non',
		'Class:FacilitiesMonitoring/Attribute:monitoring_host_snmp' => 'Le modèle se base sur SNMP ?',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect' => 'Activer la collecte électrique ?',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect+' => 'Se base sur le CI comme étant un boitierGTC et récupère l\'ensemble des PDUs lié au CI pour la collecte électrique',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect/Value:yes' => 'Oui',
		'Class:FacilitiesMonitoring/Attribute:monitoring_collecte_elect/Value:no' => 'Non',
		'Class:FacilitiesMonitoring/Attribute:modele_collect_id' => 'Le modèle de collecte électrique',
		'Class:FacilitiesMonitoring/Attribute:appsmonitoring_list' => 'Monitoring Applicatif',
		'FacilitiesMonitoring:modelehost' => 'Modèle de supervision',
		'FacilitiesMonitoring:collectelect' => 'Collecte électrique',
		
		'Class:NetworkMonitoring/Name' => '%1$s - %2$s',
		'Class:NetworkMonitoring' => 'Supervision réseau',
		'Class:NetworkMonitoring/Attribute:monitoring_host_standard_account' => 'Utiliser le compte standard ?',
		'Class:NetworkMonitoring/Attribute:monitoring_host_standard_account/Value:yes' => 'Oui',
		'Class:NetworkMonitoring/Attribute:monitoring_host_standard_account/Value:no' => 'Non',
		'Class:NetworkMonitoring/Attribute:monitoring_host_snmp' => 'Le modèle se base sur SNMP ?',
		'Class:NetworkMonitoring/Attribute:monitoring_host_ssh' => 'Le modèle se base sur SSH ?',
		'Class:NetworkMonitoring/Attribute:appsmonitoring_list' => 'Monitoring Applicatif',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools' => 'Outils de supervision',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools+' => 'Outil contenant ce CI de supervision',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools/Value:evobserv' => 'EV Observ',
		'Class:NetworkMonitoring/Attribute:network_monitoring_tools/Value:librenms' => 'Libre NMS',
		'NetworkMonitoring:modelehost' => 'Modèle de supervision',
		
		'Class:OSMonitoring/Name' => '%1$s - %2$s',
		'Class:OSMonitoring' => 'Supervision via l\'OS',
		'Class:OSMonitoring/Attribute:monitoring_host_standard_account' => 'Utiliser le compte standard ?',
		'Class:OSMonitoring/Attribute:monitoring_host_standard_account/Value:yes' => 'Oui',
		'Class:OSMonitoring/Attribute:monitoring_host_standard_account/Value:no' => 'Non',
		'Class:OSMonitoring/Attribute:monitoring_host_snmp' => 'Le modèle se base sur SNMP ?',
		'Class:OSMonitoring/Attribute:monitoring_host_wmi' => 'Le modèle se base sur WMI ?',
		'Class:OSMonitoring/Attribute:monitoring_host_ssh' => 'Le modèle se base sur SSH ?',
		'Class:OSMonitoring/Attribute:monitoring_host_api' => 'Le modèle se base sur API ?',
		'Class:OSMonitoring/Attribute:appsmonitoring_list' => 'Monitoring Applicatif',
		'OSMonitoring:modelehost' => 'Modèle de supervision',
		
		'Class:ServerMonitoring/Name' => '%1$s - %2$s',
		'Class:ServerMonitoring' => 'Supervision Out-Of-Band ilo/idrac/ipmi',
		'Class:ServerMonitoring/Attribute:monitoring_host_standard_account' => 'Utiliser le compte standard ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_standard_account/Value:yes' => 'Oui',
		'Class:ServerMonitoring/Attribute:monitoring_host_standard_account/Value:no' => 'Non',
		'Class:ServerMonitoring/Attribute:monitoring_host_snmp' => 'Le modèle se base sur SNMP ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_idrac' => 'Le modèle se base sur Idrac ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_ssh' => 'Le modèle se base sur SSH ?',
		'Class:ServerMonitoring/Attribute:monitoring_host_ipmi' => 'Le modèle se base sur IPMI ?',
		'Class:ServerMonitoring/Attribute:appsmonitoring_list' => 'Monitoring Applicatif',
		'ServerMonitoring:modelehost' => 'Modèle de supervision',
		
		'Class:VMMonitoring/Name' => '%1$s - %2$s',
		'Class:VMMonitoring' => 'Supervision via ESX/Vcenter',
		'Class:VMMonitoring/Attribute:modele_id' => 'Modèle de supervision par vcenter',
		'Class:VMMonitoring/Attribute:modele_id+' => 'Modèle d\'équipement utilisé par cette supervision par Vcenter',
		'Class:VMMonitoring/Attribute:monitoring_virtu_standard_account' => 'Utiliser le compte standard ?',
		'Class:VMMonitoring/Attribute:monitoring_virtu_standard_account/Value:yes' => 'Oui',
		'Class:VMMonitoring/Attribute:monitoring_virtu_standard_account/Value:no' => 'Non',
		'Class:VMMonitoring/Attribute:vcenter_id' => 'Nom du vcenter',
		'Class:VMMonitoring/Attribute:vcenter_id+' => 'Permet de définir l\'url du Vcenter à contacter.',
		'Class:VMMonitoring/Attribute:modele_vmwaretools_id' => 'Modèle de service de type VMWareTools',
		'Class:VMMonitoring/Attribute:modele_vmwaretools_id+' => 'Permet d\'ajouter les VMWare Tools en supervision',
		'Class:VMMonitoring/Attribute:appsmonitoring_list' => 'Monitoring Applicatif',
		'VMMonitoring:modelevirtu' => 'Modèle de supervision via VCenter',
		
		'Class:FunctionalCI/Attribute:monitoring_list' => 'Liste de supervision',
		'Class:FunctionalCI/Attribute:monitoring_list+' => 'Supervisions appliquées au CI',
		'Class:FunctionalCI/Attribute:needmonitoring' => 'Supervisé ?',
		'Class:FunctionalCI/Attribute:needmonitoring+' => 'Ce CI doit\'il être supervisé ?',
		'Class:FunctionalCI/Attribute:needmonitoring/Value:yes' => 'Oui',
		'Class:FunctionalCI/Attribute:needmonitoring/Value:no' => 'Non',
		'Class:MonitoringModele' => 'Modèle de supervision',
		'Class:MonitoringModele/Attribute:monitorings_list' => 'Liste de supervision',
		'Class:MonitoringModele/Attribute:monitorings_list+' => 'Supervision utilisant ce modèle',
		'Class:MonitoringModele/Attribute:controls_list' => 'Liste de contrôle',
		'Class:MonitoringModele/Attribute:controls_list+' => 'Contrôle utilisant ce modèle',
		'Class:MonitoringModele/Attribute:modeletype' => 'Type de Modèle',
		'Class:MonitoringModele/Attribute:modeletype/Value:equipment' => 'Equipement',
		'Class:MonitoringModele/Attribute:modeletype/Value:service' => 'Service',
		'Class:MonitoringModele/Attribute:modeletype/Value:controle' => 'Contrôle',
		'CI:Overview:Monitoring' => 'Supervision',
		'CI:Overview:Monitoring:subtitle' => 'Liste des Supervision pour ce CI',
		'BaseMonitoring:baseinfo' => 'Informations générales',
		'BaseMonitoring:modele' => 'Modèle d\'equipement',
		'VMMonitoring:control' => 'Modèle de contrôle d\'equipement',
) );
?>
