<?php
// PHP Data Model definition file
// WARNING - WARNING - WARNING
// DO NOT EDIT THIS FILE (unless you know what you are doing)
//
// If you use supply a datamodel.xxxx.xml file with your module
// the this file WILL BE overwritten by the compilation of the
// module (during the setup) if the datamodel.xxxx.xml file
// contains the definition of new classes or menus.
//
// The recommended way to define new classes (for iTop 2.0) is via the XML definition.
// This file remains in the module's template only for the cases where there is:
// - either no new class or menu defined in the XML file
// - or no XML file at all supplied by the module
class Monitoringplugin implements iApplicationUIExtension {

	public function OnDisplayProperties(
			$oObject,
			WebPage $oPage,
			$bEditMode = false) {
	}

	public function OnDisplayRelations(
			$oObject,
			WebPage $oPage,
			$bEditMode = false) {
		if (in_array ( get_class ( $oObject ), array (
				'BaseMonitoring',
				'ControlMonitoring',
				'FacilitiesMonitoring',
				'NetworkMonitoring',
				'OSMonitoring',
				'ServerMonitoring',
				'VMMonitoring'
		) )) {
			//La configuration de ev observe bloque l'acces en iframe
			$oPage->SetCurrentTab ( Dict::S ( 'Monitoring URL' ) );
			$sMonitoringURL = MetaModel::GetModuleSetting ( 'Monitoring', 'monitoring_url', '' );
			$sHostURL = $sMonitoringURL . 'main.php?p=10299&idcompany=2#hostId=' . $oObject->Get ( 'monitoring_id' );
			$oPage->add ( "<div id=\"monitoring\" class=\"resizable\" style=\"height:1000px;\"><iframe src=\"$sHostURL\" style=\"width:100%;height:100%;\"></iframe></div>" );
		}
	}

	public function OnFormSubmit(
			$oObject,
			$sFormPrefix = '') {
	}

	public function OnFormCancel(
			$sTempId) {
	}

	public function EnumUsedAttributes(
			$oObject) {
		return array ();
	}

	public function GetIcon(
			$oObject) {
		return '';
	}

	public function GetHilightClass(
			$oObject) {
		// Possible return values are:
		// HILIGHT_CLASS_CRITICAL, HILIGHT_CLASS_WARNING, HILIGHT_CLASS_OK, HILIGHT_CLASS_NONE
		return HILIGHT_CLASS_NONE;
	}

	public function EnumAllowedActions(
			DBObjectSet $oSet) {
		return array ();
	}
}
