<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'EN US', 'English', 'English', array (
		'Menu:Climatisation' => 'Air Conditioning',
		'Class:Climatisation' => 'Air Cond',
		'Class:Climatisation+' => '',
		//'Class:Climatisation/Name' => '%2$s - %1$s - %3$s',
		'Class:Climatisation/Attribute:powerstart_id' => 'Electrical source',
		'Class:Climatisation/Attribute:powerstart_id+' => '',
		'Class:Climatisation/Attribute:powerstart_name' => 'Electrical source name',
		'Class:Climatisation/Attribute:powerstart_name+' => '',
		'Class:Climatisation/Attribute:fqdn' => 'FQDN',
		'Class:Climatisation/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:Climatisation/Attribute:facilities_id' => 'Facilities Reference',
		'Class:Climatisation/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:ArmoireClim' => 'Air Cond cabinet',
		'Class:ArmoireClim+' => '',
		//'Class:ArmoireClim/Name' => '%2$s - %1$s - %3$s',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_id' => 'Fresh Water Circuit A',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_id+' => '',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_name' => 'Fresh Water Circuit name A',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_name+' => '',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_id' => 'Fresh Water Circuit B',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_id+' => '',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_name' => 'Fresh Water Circuit name B',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_name+' => '',
		'Class:ArmoireClim/Attribute:redundancy' => 'Redundancy',
		'Class:ArmoireClim/Attribute:redundancy/count' => 'The device is up if at least one Fresh Water Circuit (A or B) is up',
		'Class:ArmoireClim/Attribute:powerstart_id' => 'Electrical source',
		'Class:ArmoireClim/Attribute:powerstart_id+' => '',
		'Class:ArmoireClim/Attribute:powerstart_name' => 'Electrical source name',
		'Class:ArmoireClim/Attribute:powerstart_name+' => '',
		'Class:ArmoireClim/Attribute:fqdn' => 'FQDN',
		'Class:ArmoireClim/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:ArmoireClim/Attribute:facilities_id' => 'Facilities Reference',
		'Class:ArmoireClim/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:BallonEauGlace' => 'Fresh Water Balloon',
		'Class:BallonEauGlace+' => '',
		//'Class:BallonEauGlace/Name' => '%2$s - %1$s - %3$s',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_id' => 'Fresh Water Circuit source',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_id+' => '',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_name' => 'Fresh Water Circuit source name',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_name+' => '',
		'Class:BallonEauGlace/Attribute:PompeClim_list' => 'Air Cond Pump',
		'Class:BallonEauGlace/Attribute:PompeClim_list+' => '',
		'Class:BallonEauGlace/Attribute:GroupeEauGlace_list' => 'Fresh Water Groups',
		'Class:BallonEauGlace/Attribute:GroupeEauGlace_list+' => '',
		'Class:BallonEauGlace/Attribute:redundancy' => 'High availability',
		'Class:BallonEauGlace/Attribute:redundancy/disabled' => 'The Fresh Water Ballon is up if all the Fresh Water Groups are up',
		'Class:BallonEauGlace/Attribute:redundancy/count' => 'The Fresh Water Ballon is up if at least %1$s Fresh Water Group(s) is(are) up',
		'Class:BallonEauGlace/Attribute:redundancy/percent' => 'The Fresh Water Ballon is up if at least %1$s %% of the Fresh Water Groups are up',
		'Class:BallonEauGlace/Attribute:redundancy+' => '',
		'Class:BallonEauGlace/Attribute:facilities_id' => 'Facilities Reference',
		'Class:BallonEauGlace/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:CircuitEauGlace' => 'Fresh Water Circuit',
		'Class:CircuitEauGlace+' => '',
		//'Class:CircuitEauGlace/Name' => '%2$s - %1$s - %3$s',
		'Class:CircuitEauGlace/Attribute:facilities_id' => 'Facilities Reference',
		'Class:CircuitEauGlace/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_id' => 'Air Cond Pump',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_id+' => '',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_name' => 'Air Cond Pump name',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_name+' => '',
		'Class:GroupeEauGlace' => 'Fresh Water Group',
		'Class:GroupeEauGlace+' => '',
		//'Class:GroupeEauGlace/Name' => '%2$s - %1$s - %3$s',
		'Class:GroupeEauGlace/Attribute:balloneauglace_id' => 'Fresh Water Balloon',
		'Class:GroupeEauGlace/Attribute:balloneauglace_id+' => '',
		'Class:GroupeEauGlace/Attribute:balloneauglace_name' => 'Fresh Water Balloon name',
		'Class:GroupeEauGlace/Attribute:balloneauglace_name+' => '',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_id' => 'Fresh Water Circuit',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_id+' => '',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_name' => 'Fresh Water Circuit name',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_name+' => '',
		'Class:GroupeEauGlace/Attribute:powerstart_id' => 'Electrical source',
		'Class:GroupeEauGlace/Attribute:powerstart_id+' => '',
		'Class:GroupeEauGlace/Attribute:powerstart_name' => 'Electrical source name',
		'Class:GroupeEauGlace/Attribute:powerstart_name+' => '',
		'Class:GroupeEauGlace/Attribute:facilities_id' => 'Facilities Reference',
		'Class:GroupeEauGlace/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:PompeClim' => 'Air Cond Pump',
		'Class:PompeClim+' => 'Air Conditionning pump',
		//'Class:PompeClim/Name' => '%2$s - %1$s - %3$s',
		'Class:PompeClim/Attribute:balloneauglace_id' => 'Fresh Water Balloon',
		'Class:PompeClim/Attribute:balloneauglace_id+' => '',
		'Class:PompeClim/Attribute:balloneauglace_name' => 'Fresh Water Balloon name',
		'Class:PompeClim/Attribute:balloneauglace_name+' => '',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_id' => 'Primary Fresh Water Circuit',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_id+' => '',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_name' => 'Primary Fresh Water Circuit name',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_name+' => '',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_id' => 'Secondary Fresh Water Circuit',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_id+' => '',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_name' => 'Secondary Fresh Water Circuit name',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_name+' => '',
		'Class:PompeClim/Attribute:powerstart_id' => 'Electrical source',
		'Class:PompeClim/Attribute:powerstart_id+' => '',
		'Class:PompeClim/Attribute:powerstart_name' => 'Electrical source name',
		'Class:PompeClim/Attribute:powerstart_name+' => '',
		'Class:PompeClim/Attribute:facilities_id' => 'Facilities Reference',
		'Class:PompeClim/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
) );
?>
