<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'FR FR', 'French', 'Français', array (
		'Menu:Climatisation' => 'Eau glacée',
		'Class:Climatisation' => 'Climatisation',
		'Class:Climatisation+' => '',
		//'Class:Climatisation/Name' => '%2$s - %1$s - %3$s',
		'Class:Climatisation/Attribute:powerstart_id' => 'Alimentation électrique',
		'Class:Climatisation/Attribute:powerstart_id+' => '',
		'Class:Climatisation/Attribute:powerstart_name' => 'Nom de l\'alimentation électrique',
		'Class:Climatisation/Attribute:powerstart_name+' => '',
		'Class:Climatisation/Attribute:fqdn' => 'FQDN',
		'Class:Climatisation/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:Climatisation/Attribute:facilities_id' => 'Référence Facilities',
		'Class:Climatisation/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:ArmoireClim' => 'Armoire Clim',
		'Class:ArmoireClim+' => '',
		//'Class:ArmoireClim/Name' => '%2$s - %1$s - %3$s',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_id' => 'Circuit eau Glacée A',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_id+' => '',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_name' => 'Nom Circuit eau Glacé A',
		'Class:ArmoireClim/Attribute:circuiteaunglaceA_name+' => '',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_id' => 'Circuit eau Glacée B',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_id+' => '',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_name' => 'Nom Circuit eau Glacé B',
		'Class:ArmoireClim/Attribute:circuiteaunglaceB_name+' => '',
		'Class:ArmoireClim/Attribute:redundancy' => 'Redondance',
		'Class:ArmoireClim/Attribute:redundancy/count' => 'L\'%2$s est alimentée si au moins un circuit d\'eau glacée (A ou B) est opérationnel',
		'Class:ArmoireClim/Attribute:powerstart_id' => 'Alimentation électrique',
		'Class:ArmoireClim/Attribute:powerstart_id+' => '',
		'Class:ArmoireClim/Attribute:powerstart_name' => 'Nom de l\'alimentation électrique',
		'Class:ArmoireClim/Attribute:powerstart_name+' => '',
		'Class:ArmoireClim/Attribute:fqdn' => 'FQDN',
		'Class:ArmoireClim/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:ArmoireClim/Attribute:facilities_id' => 'Référence Facilities',
		'Class:ArmoireClim/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:BallonEauGlace' => 'Ballon d\'eau Glacée',
		'Class:BallonEauGlace+' => '',
		//'Class:BallonEauGlace/Name' => '%2$s - %1$s - %3$s',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_id' => 'Circuit eau Glacée d\'alimentation',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_id+' => '',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_name' => 'Nom Circuit eau Glacé d\'alimentation',
		'Class:BallonEauGlace/Attribute:circuiteaunglace_name+' => '',
		'Class:BallonEauGlace/Attribute:PompeClim_list' => 'Pompes de climatisation',
		'Class:BallonEauGlace/Attribute:PompeClim_list+' => '',
		'Class:BallonEauGlace/Attribute:GroupeEauGlace_list' => 'Groupes d\'eau glacée',
		'Class:BallonEauGlace/Attribute:GroupeEauGlace_list+' => '',
		'Class:BallonEauGlace/Attribute:redundancy' => 'Haute disponibilité',
		'Class:BallonEauGlace/Attribute:redundancy/disabled' => 'Le Ballon d\'eau glacée est opérationnel si tous les Groupes d\'eau glacées qui le composent sont opérationnels',
		'Class:BallonEauGlace/Attribute:redundancy/count' => 'Nombre minimal de Groupes d\'eau glacées pour que le Ballon d\'eau glacée soit opérationnel : %1$s',
		'Class:BallonEauGlace/Attribute:redundancy/percent' => 'Pourcentage minimal de Groupes d\'eau glacées pour que le Ballon d\'eau glacée soit opérationnel : %1$s %%',
		'Class:BallonEauGlace/Attribute:facilities_id' => 'Référence Facilities',
		'Class:BallonEauGlace/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:CircuitEauGlace' => 'Circuit Eau Glacée',
		'Class:CircuitEauGlace+' => '',
		//'Class:CircuitEauGlace/Name' => '%2$s - %1$s - %3$s',
		'Class:CircuitEauGlace/Attribute:facilities_id' => 'Référence Facilities',
		'Class:CircuitEauGlace/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_id' => 'Pompe de Clim',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_id+' => '',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_name' => 'Nom Pompe de Clim',
		// 'Class:CircuitEauGlace/Attribute:pompeclim_name+' => '',
		'Class:GroupeEauGlace' => 'Groupe d\'eau glacée',
		'Class:GroupeEauGlace+' => '',
		//'Class:GroupeEauGlace/Name' => '%2$s - %1$s - %3$s',
		'Class:GroupeEauGlace/Attribute:balloneauglace_id' => 'Ballon d\'eau glacée',
		'Class:GroupeEauGlace/Attribute:balloneauglace_id+' => '',
		'Class:GroupeEauGlace/Attribute:balloneauglace_name' => 'Nom du Ballon d\'eau glacée',
		'Class:GroupeEauGlace/Attribute:balloneauglace_name+' => '',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_id' => 'Circuit eau Glacée',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_id+' => '',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_name' => 'Nom Circuit eau Glacé',
		'Class:GroupeEauGlace/Attribute:circuiteaunglace_name+' => '',
		'Class:GroupeEauGlace/Attribute:powerstart_id' => 'Alimentation électrique',
		'Class:GroupeEauGlace/Attribute:powerstart_id+' => '',
		'Class:GroupeEauGlace/Attribute:powerstart_name' => 'Electrical source name',
		'Class:GroupeEauGlace/Attribute:powerstart_name+' => '',
		'Class:GroupeEauGlace/Attribute:facilities_id' => 'Référence Facilities',
		'Class:GroupeEauGlace/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:PompeClim' => 'Pompe Clim',
		'Class:PompeClim+' => 'Pompe de Climatisation',
		//'Class:PompeClim/Name' => '%2$s - %1$s - %3$s',
		'Class:PompeClim/Attribute:balloneauglace_id' => 'Ballon d\'eau glacée',
		'Class:PompeClim/Attribute:balloneauglace_id+' => '',
		'Class:PompeClim/Attribute:balloneauglace_name' => 'Nom du Ballon d\'eau glacée',
		'Class:PompeClim/Attribute:balloneauglace_name+' => '',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_id' => 'Circuit eau Glacée primaire',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_id+' => '',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_name' => 'Nom Circuit eau Glacé primaire',
		'Class:PompeClim/Attribute:circuiteaunglaceprimaire_name+' => '',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_id' => 'Circuit eau Glacée secondaire',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_id+' => '',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_name' => 'Nom Circuit eau Glacé secondaire',
		'Class:PompeClim/Attribute:circuiteaunglacesecondaire_name+' => '',
		'Class:PompeClim/Attribute:powerstart_id' => 'Alimentation électrique',
		'Class:PompeClim/Attribute:powerstart_id+' => '',
		'Class:PompeClim/Attribute:powerstart_name' => 'Nom de l\'alimentation électrique',
		'Class:PompeClim/Attribute:powerstart_name+' => '',
		'Class:PompeClim/Attribute:facilities_id' => 'Référence Facilities',
		'Class:PompeClim/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
) );
?>
