<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

// Risk class
Dict::Add('EN US', 'English', 'English', array(
	'Class:Risk' => 'Risk',
	'Class:Risk/Attribute:CheckNextUpdate' => 'Check next update date',
	'Class:Risk/Attribute:CheckTriggerdate' => 'Check risk trigger date',
	'Class:Risk/Attribute:close_date' => 'Close date',
	'Class:Risk/Attribute:cost_impact' => 'Cost impact',
	'Class:Risk/Attribute:cost_impact+' => 'Cost impact if risk occurs',
	'Class:Risk/Attribute:description' => 'Description',
	'Class:Risk/Attribute:identifier_id' => 'Identified by',
	'Class:Risk/Attribute:impact' => 'Impact description',
	'Class:Risk/Attribute:impact_rating' => 'Impact rating',
	'Class:Risk/Attribute:impact_rating/Value:1' => 'High',
	'Class:Risk/Attribute:impact_rating/Value:2' => 'Medium',
	'Class:Risk/Attribute:impact_rating/Value:3' => 'Low',
	'Class:Risk/Attribute:impact_rating+' => 'Describes impact  rate if risk occurs',
	'Class:Risk/Attribute:int_ext' => 'Internal or external',
	'Class:Risk/Attribute:int_ext/Value:external' => 'External',
	'Class:Risk/Attribute:int_ext/Value:internal' => 'Internal',
	'Class:Risk/Attribute:last_update' => 'Last update',
	'Class:Risk/Attribute:next_update' => 'Next update due date',
	'Class:Risk/Attribute:org_id' => 'Customer',
	'Class:Risk/Attribute:overall_rating' => 'Overall risk rating',
	'Class:Risk/Attribute:overall_rating/Value:1' => 'Critical',
	'Class:Risk/Attribute:overall_rating/Value:2' => 'High',
	'Class:Risk/Attribute:overall_rating/Value:3' => 'Medium',
	'Class:Risk/Attribute:overall_rating/Value:4' => 'Low',
	'Class:Risk/Attribute:owner_id' => 'Owner',
	'Class:Risk/Attribute:probability_rating' => 'Probability rating',
	'Class:Risk/Attribute:probability_rating/Value:1' => 'High',
	'Class:Risk/Attribute:probability_rating/Value:2' => 'Medium',
	'Class:Risk/Attribute:probability_rating/Value:3' => 'Low',
	'Class:Risk/Attribute:probability_rating+' => 'Describes probability the risk occurs',
	'Class:Risk/Attribute:project_id' => 'Project',
	'Class:Risk/Attribute:ref' => 'Ref',
	'Class:Risk/Attribute:reject_reason' => 'Rejection reason',
	'Class:Risk/Attribute:resolution_code' => 'Resolution code',
	'Class:Risk/Attribute:resolution_code/Value:avoided' => 'Avoided',
	'Class:Risk/Attribute:resolution_code/Value:cancel' => 'Not anymore risk/cancelled',
	'Class:Risk/Attribute:resolution_code/Value:issue' => 'Occured and treated',
	'Class:Risk/Attribute:resolution_code/Value:notoccured' => 'Not occured',
	'Class:Risk/Attribute:resolution_code/Value:rejected' => 'Not applicable- rejected',
	'Class:Risk/Attribute:resolution_code/Value:transferred' => 'Transferred',
	'Class:Risk/Attribute:response_description' => 'Response plan description',
	'Class:Risk/Attribute:response_strategy' => 'Response strategy',
	'Class:Risk/Attribute:response_strategy/Value:accept' => 'Accept',
	'Class:Risk/Attribute:response_strategy/Value:avoid' => 'Avoid',
	'Class:Risk/Attribute:response_strategy/Value:mitigate' => 'Mitigate',
	'Class:Risk/Attribute:response_strategy/Value:transfer' => 'Transfer',
	'Class:Risk/Attribute:revised_risk_EMV' => 'Revised risk EMV',
	'Class:Risk/Attribute:revised_risk_EMV+' => 'Revised risk expected monetary value',
	'Class:Risk/Attribute:risk_calculated_EMV' => 'Calculated risk EMV',
	'Class:Risk/Attribute:risk_calculated_EMV+' => 'Calculated risk expected monetary value',
	'Class:Risk/Attribute:risk_owner_id' => 'Owner',
	'Class:Risk/Attribute:risk_probability' => 'Risk probability (%)',
	'Class:Risk/Attribute:risk_probability+' => '% risk occurs',
	'Class:Risk/Attribute:start_date' => 'Creation date',
	'Class:Risk/Attribute:status' => 'Status',
	'Class:Risk/Attribute:status/Value:analysed' => 'Analyzed',
	'Class:Risk/Attribute:status/Value:cancelled' => 'Cancelled',
	'Class:Risk/Attribute:status/Value:closed' => 'Closed',
	'Class:Risk/Attribute:status/Value:inprogress' => 'In Progress',
	'Class:Risk/Attribute:status/Value:new' => 'New',
	'Class:Risk/Attribute:status/Value:rejected' => 'Rejected',
	'Class:Risk/Attribute:threat_opportunity' => 'Threat or opportunity',
	'Class:Risk/Attribute:threat_opportunity/Value:opportunity' => 'Opportunity',
	'Class:Risk/Attribute:threat_opportunity/Value:threat' => 'Threat',
	'Class:Risk/Attribute:title' => 'Title',
	'Class:Risk/Attribute:trigger_date' => 'Trigger date',
	'Class:Risk/Attribute:trigger_date+' => 'Boundary date where risk will become issue',
	'Class:Risk/Attribute:trigger_description' => 'Trigger description',
	'Class:Risk/Attribute:trigger_description+' => 'Describe why you consider risk becomes an issue at this date',
	'Class:Risk/Attribute:type' => 'Type',
	'Class:Risk/Attribute:type/Value:issue' => 'Issue',
	'Class:Risk/Attribute:type/Value:risk' => 'Risk',
	'Class:Risk/Attribute:wbss_list' => 'Deliverables',
	'Class:Risk/Name' => '%1$s',
	'Class:Risk/Stimulus:ev_analyse' => 'Analyse',
	'Class:Risk/Stimulus:ev_cancel' => 'Cancel',
	'Class:Risk/Stimulus:ev_close' => 'Close',
	'Class:Risk/Stimulus:ev_progress' => 'In progress',
	'Class:Risk/Stimulus:ev_reject' => 'Reject',
	'Class:Risk/Stimulus:ev_reopen' => 'Re-open',
	'Risk:Contacts' => 'Contacts',
	'Risk:Date' => 'Dates',
	'Risk:Info' => 'Information',
	'Risk:Qualification' => 'Qualification',
	'Risk:ResponsePlan' => 'Response Plan',

	'Class:lnkRiskToWBS' => 'Link Risk to WBS',
	'Class:lnkRiskToWBS/Attribute:risk_id' => 'Issue or Risk',
	'Class:lnkRiskToWBS/Attribute:risk_id_finalclass_recall' => 'Finalclass',
	'Class:lnkRiskToWBS/Attribute:title' => 'Title',
	'Class:lnkRiskToWBS/Attribute:wbs_id' => 'Deliverable',
	'Class:lnkRiskToWBS/Name' => '%1$s - %2$s',

	'Menu:MyRisk' => 'My risks',
	'Menu:MyRisk+' => 'My owned risks',
	'Menu:NewRisk' => 'New risk',
	'Menu:RiskMenu' => 'Risk',
	'Menu:SearchRisk' => 'Search risk',
	'UI-RiskManagementOverview-OpenRiskByProject' => 'Open risks by customer project',
	'UI-RiskManagementOverview-RiskToIssue' => 'Risks that may become Issues this week',
	'UI-RiskManagementOverview-RiskToUpdate' => 'Risks that should be updated this week',

	'Class:Risk/CreateIssue' => 'Create issue',
	'Class:Risk/CreateIssueForm' =>'Create an issue from %1$s',
	'Class:Risk/ReportLabel' => 'Created from %1$s',
));

// Project class
Dict::Add('EN US', 'English', 'English', array(
	'Class:Project/Attribute:contingency_reserve' => 'Contingency reserve  (calculated risk budget)',
	'Class:Project/Attribute:contingency_reserve+' => 'Add  risks costs (except risks  avoid or transferred)',
	'Class:Project/Attribute:risks_costs' => 'Risks costs',
	'Class:Project/Attribute:risks_list' => 'Risks',
	'Class:Project/Attribute:risks_list_displaybare' => 'Risks not closed nor rejected, linked to a non closed deliverable, where response strategy is not avoid nor transferred',
	'Class:Project/Attribute:issues_costs' => 'Open issues costs',
	'Class:Project/Attribute:issues_costs+' => 'Costs of opened issues',
	'Class:Project/Attribute:issues_list' => 'Issues related',
	'Class:Project/Attribute:issues_list_displaybare' => 'Issues not closed nor rejected, linked to a non closed deliverable, where response strategy is not avoid nor transferred',
	'Class:Project/Attribute:person_id' => 'Sponsor',
	'Class:Project/Attribute:private_log' => 'Project log',
	'Class:Project/Attribute:revised_budget' => 'Revised budget',	
	'Class:Project:Display:accepted_risks'  =>  'Costs of open "accepted/mitigated" risks',
	'Class:Project:Display:issue_costs' => 'Costs of open issues',	
	'Class:Project/Attribute:costs_spent' => 'Issues costs already spent',
	'Class:Project/Attribute:costs_spent+' => 'Costs of closed issues added',
	'Project:Display:delivrables_costs' => 'Costs of all deliverables',

));

// ProjectChange class
Dict::Add('EN US', 'English', 'English', array(
	'Class:ProjectChange' => 'Project change',
	'Class:ProjectChange/Attribute:impact_project' => 'Dimension impact',
	'Class:ProjectChange/Attribute:impact_project/Value:cost' => 'Costs',
	'Class:ProjectChange/Attribute:impact_project/Value:schedule' => 'Schedule',
	'Class:ProjectChange/Attribute:impact_project/Value:scope' => 'Scope',
	'Class:ProjectChange/Attribute:impact_project+' => 'Main impact on this dimension',
	'Class:ProjectChange/Attribute:project_id' => 'Project',
	'Class:ProjectChange/Attribute:resolution_plan' => 'Approval plan',
	'Class:ProjectChange/Attribute:wbss_list' => 'Deliverables',
	'Class:ProjectChange/Name' => '%1$s',
	'Class:ProjectChange/Stimulus:ev_approve' => 'Approve',
	'Class:ProjectChange/Stimulus:ev_assign' => 'Assign',
	'Class:ProjectChange/Stimulus:ev_close' => 'Close',
	'Class:ProjectChange/Stimulus:ev_plan' => 'Plan',
	'Class:ProjectChange/Stimulus:ev_reject' => 'Reject',
	'Class:ProjectChange/Stimulus:ev_reopen' => 'Re open',
	'Class:ProjectChange+' => 'Change on project',

	'Class:lnkProjectChangeToWBS' => 'Link ProjectChange To WBS',
	'Class:lnkProjectChangeToWBS/Attribute:projectchange_id' => 'Project change',
	'Class:lnkProjectChangeToWBS/Attribute:wbs_id' => 'Deliverable',
	'Class:lnkProjectChangeToWBS/Name' => '%1$s - %2$s',

	'Menu:MyProjectChange' => 'Project changes assigned to me',
	'Menu:MyProjectChange+' => 'Project changes assigned to me',
	'Menu:NewProjectChange' => 'New project change',
	'Menu:ProjectChangeMenu' => 'Project change',
	'Menu:SearchProjectChange' => 'Search for project change',
));

// WBS class
Dict::Add('EN US', 'English', 'English', array(
	'Class:WBS/Attribute:projectchanges_list' => 'Project changes',
	'Class:WBS/Attribute:risks_list' => 'Risks',
));
