<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

// Risk class
Dict::Add('FR FR', 'French', 'Français', array(
	'Class:Risk' => 'Risque',
	'Class:Risk/Attribute:CheckNextUpdate' => 'Prochaine date de mise à jour du risque',
	'Class:Risk/Attribute:CheckTriggerdate' => 'Prochaine date de déclenchement du risque',
	'Class:Risk/Attribute:close_date' => 'Date de clôture',
	'Class:Risk/Attribute:cost_impact' => 'Impact de coûts',
	'Class:Risk/Attribute:cost_impact+' => 'Impact financier si le risque est avéré',
	'Class:Risk/Attribute:description' => 'Description',
	'Class:Risk/Attribute:identifier_id' => 'Identifié par',
	'Class:Risk/Attribute:impact' => 'Description de l\'impact',
	'Class:Risk/Attribute:impact_rating' => 'Echelle d\'impact',
	'Class:Risk/Attribute:impact_rating/Value:1' => 'Elevé',
	'Class:Risk/Attribute:impact_rating/Value:2' => 'Moyen',
	'Class:Risk/Attribute:impact_rating/Value:3' => 'Faible',
	'Class:Risk/Attribute:impact_rating+' => 'Importance de l\'impact si le risque est avéré',
	'Class:Risk/Attribute:int_ext' => 'Interne ou externe',
	'Class:Risk/Attribute:int_ext/Value:external' => 'Externe',
	'Class:Risk/Attribute:int_ext/Value:internal' => 'Interne',
	'Class:Risk/Attribute:last_update' => 'Dernière mise à jour',
	'Class:Risk/Attribute:next_update' => 'Prochaine date de mise à jour',
	'Class:Risk/Attribute:org_id' => 'Client',
	'Class:Risk/Attribute:overall_rating' => 'Estimation du risque',
	'Class:Risk/Attribute:overall_rating/Value:1' => 'Critique',
	'Class:Risk/Attribute:overall_rating/Value:2' => 'Elevé',
	'Class:Risk/Attribute:overall_rating/Value:3' => 'Moyen',
	'Class:Risk/Attribute:overall_rating/Value:4' => 'Faible',
	'Class:Risk/Attribute:owner_id' => 'Responsable',
	'Class:Risk/Attribute:probability_rating' => 'Niveau de probabilité',
	'Class:Risk/Attribute:probability_rating/Value:1' => 'Elevé',
	'Class:Risk/Attribute:probability_rating/Value:2' => 'Moyen',
	'Class:Risk/Attribute:probability_rating/Value:3' => 'Faible',
	'Class:Risk/Attribute:probability_rating+' => 'Probabilité que le risque soit avéré',
	'Class:Risk/Attribute:project_id' => 'Projet',
	'Class:Risk/Attribute:ref' => 'Référence',
	'Class:Risk/Attribute:reject_reason' => 'Raison du refus',
	'Class:Risk/Attribute:resolution_code' => 'Code de résolution',
	'Class:Risk/Attribute:resolution_code/Value:avoided' => 'Evité',
	'Class:Risk/Attribute:resolution_code/Value:cancel' => 'Plus de risque/ annulation',
	'Class:Risk/Attribute:resolution_code/Value:issue' => 'Avéré et géré',
	'Class:Risk/Attribute:resolution_code/Value:notoccured' => 'Le risque ne s\'est pas produit',
	'Class:Risk/Attribute:resolution_code/Value:rejected' => 'Non applicable / rejeté',
	'Class:Risk/Attribute:resolution_code/Value:transferred' => 'Transferré',
	'Class:Risk/Attribute:response_description' => 'Description de réponse au risque',
	'Class:Risk/Attribute:response_strategy' => 'Stratégie de réponse au risque',
	'Class:Risk/Attribute:response_strategy/Value:accept' => 'Acceptation',
	'Class:Risk/Attribute:response_strategy/Value:avoid' => 'Evitement',
	'Class:Risk/Attribute:response_strategy/Value:mitigate' => 'Atténuation',
	'Class:Risk/Attribute:response_strategy/Value:transfer' => 'Transfert',
	'Class:Risk/Attribute:revised_risk_EMV' => 'Coût EMV du risque ré-évalué',
	'Class:Risk/Attribute:revised_risk_EMV+' => 'Valeur monétaire attendue du risque réévaluée',
	'Class:Risk/Attribute:risk_calculated_EMV' => 'Coût calculé EMV du risque',
	'Class:Risk/Attribute:risk_calculated_EMV+' => 'Valeur monétaire attendue du risque',
	'Class:Risk/Attribute:risk_owner_id' => 'Responsable',
	'Class:Risk/Attribute:risk_probability' => 'Probabilité du risque (%)',
	'Class:Risk/Attribute:risk_probability+' => '%probabilité que le risque soit avéré',
	'Class:Risk/Attribute:start_date' => 'Date de création',
	'Class:Risk/Attribute:status' => 'Statut',
	'Class:Risk/Attribute:status/Value:analysed' => 'Analysé',
	'Class:Risk/Attribute:status/Value:cancelled' => 'Annulé',
	'Class:Risk/Attribute:status/Value:closed' => 'Clos',
	'Class:Risk/Attribute:status/Value:inprogress' => 'En cours',
	'Class:Risk/Attribute:status/Value:new' => 'Nouveau',
	'Class:Risk/Attribute:status/Value:rejected' => 'Rejeté',
	'Class:Risk/Attribute:threat_opportunity' => 'Menace ou opportunité',
	'Class:Risk/Attribute:threat_opportunity/Value:opportunity' => 'Opportunité',
	'Class:Risk/Attribute:threat_opportunity/Value:threat' => 'Menace',
	'Class:Risk/Attribute:title' => 'Titre',
	'Class:Risk/Attribute:trigger_date' => 'Date de déclenchement',
	'Class:Risk/Attribute:trigger_date+' => 'Date limite à laquelle le risque devient avéré',
	'Class:Risk/Attribute:trigger_description' => 'Description du déclenchement',
	'Class:Risk/Attribute:trigger_description+' => 'Décrire pourquoi le risque devient avéré à cette date',
	'Class:Risk/Attribute:type' => 'Type',
	'Class:Risk/Attribute:type/Value:issue' => 'Risque avéré',
	'Class:Risk/Attribute:type/Value:risk' => 'Risque',
	'Class:Risk/Attribute:wbss_list' => 'Livrables',
	'Class:Risk/Name' => '%1$s',
	'Class:Risk/Stimulus:ev_analyse' => 'Analyser',
	'Class:Risk/Stimulus:ev_cancel' => 'Annuler',
	'Class:Risk/Stimulus:ev_close' => 'Clore',
	'Class:Risk/Stimulus:ev_progress' => 'En cours',
	'Class:Risk/Stimulus:ev_reject' => 'Rejeter',
	'Class:Risk/Stimulus:ev_reopen' => 'Ré-ouvrir',
	'Risk:Contacts' => 'Contacts',
	'Risk:Date' => 'Dates',
	'Risk:Info' => 'Informations',
	'Risk:Qualification' => 'Qualification',
	'Risk:ResponsePlan' => 'Plan de réponse',

	'Class:lnkRiskToWBS' => 'Link Risk to WBS',
	'Class:lnkRiskToWBS/Attribute:risk_id' => 'Risques',
	'Class:lnkRiskToWBS/Attribute:risk_id_finalclass_recall' => '',
	'Class:lnkRiskToWBS/Attribute:title' => '',
	'Class:lnkRiskToWBS/Attribute:wbs_id' => 'Deliverable',
	'Class:lnkRiskToWBS/Name' => '%1$s - %2$s',

	'Menu:MyRisk' => 'Mes risques',
	'Menu:MyRisk+' => 'Les risques dont je suis responsable',
	'Menu:NewRisk' => 'Nouveau risque',
	'Menu:RiskMenu' => 'Risques',
	'Menu:SearchRisk' => 'Rechercher des risques',
	'UI-RiskManagementOverview-OpenRiskByProject' => 'Risques ouverts par projet ',
	'UI-RiskManagementOverview-RiskToIssue' => 'Risques qui seront avérés cette semaine',
	'UI-RiskManagementOverview-RiskToUpdate' => 'Risques devant être mis à jour cette semaine',

	'Class:Risk/CreateIssue' => 'Créer une issue...',
	'Class:Risk/CreateIssueForm' =>'Créer une issue depuis %1$s',
	'Class:Risk/ReportLabel' => 'Créé depuis %1$s',
));

// Project class
Dict::Add('FR FR', 'French', 'Français', array(
	'Class:Project/Attribute:contingency_reserve' => 'Réserve pour aléa (budget de risques calculé)',
	'Class:Project/Attribute:contingency_reserve+' => 'calcule la somme des coûts des risques (sauf ceux évités ou transférés) ',
	'Class:Project/Attribute:risks_costs' => 'Coûts des risques',
	'Class:Project/Attribute:risks_list' => 'Risques ',
	'Class:Project/Attribute:risks_list_displaybare' => 'Risques non clos ni rejetés, dont la stratégie de réponse n\'est ni le transfert ni l\'évitement ',
	'Class:Project/Attribute:issues_costs' => 'Coûts des risques avérés en cours',
	'Class:Project/Attribute:issues_costs+' => 'Costs of opened issues',
	'Class:Project/Attribute:issues_list' => 'Risques avérés',
	'Class:Project/Attribute:issues_list_displaybare' => 'Risques avérés non clos ni rejetés, dont la stratégie de réponse n\'est ni le transfert ni l\'évitement',
	'Class:Project/Attribute:person_id' => 'Sponsor',
	'Class:Project/Attribute:private_log' => 'Log',
	'Class:Project/Attribute:revised_budget' => 'Budget revu',
	'Class:Project:Display:accepted_risks' => 'Coûts des risques "acceptés/atténués"',	
	'Class:Project:Display:issue_costs' => 'Coûts des risques avérés en cours',
	'Class:Project/Attribute:costs_spent' => 'Coûts des risques avérés déjà dépensés',
	'Class:Project/Attribute:costs_spent+' => 'Les coûts sont déjà dépensés donc additionnés',
	'Project:Display:delivrables_costs' => 'Coûts de tous les livrables',
));

// ProjectChange class
Dict::Add('FR FR', 'French', 'Français', array(
	'Class:ProjectChange' => 'Changement sur projet',
	'Class:ProjectChange/Attribute:impact_project' => 'Impact sur la dimension',
	'Class:ProjectChange/Attribute:impact_project/Value:cost' => 'Coûts',
	'Class:ProjectChange/Attribute:impact_project/Value:schedule' => 'Echéancier',
	'Class:ProjectChange/Attribute:impact_project/Value:scope' => 'Périmètre',
	'Class:ProjectChange/Attribute:impact_project+' => 'Impact principal sur la dimension sélectionnée',
	'Class:ProjectChange/Attribute:project_id'  =>  'Projet',
	'Class:ProjectChange/Attribute:resolution_plan'  =>  'Planning d\'approbation',
    'Class:ProjectChange/Attribute:wbss_list'  =>  'Livrables',
	'Class:ProjectChange/Name' => '%1$s',
	'Class:ProjectChange/Stimulus:ev_approve' => 'Approuver',
	'Class:ProjectChange/Stimulus:ev_assign' => 'Assigner',
	'Class:ProjectChange/Stimulus:ev_close' => 'Clore',
	'Class:ProjectChange/Stimulus:ev_plan' => 'Planifier',
	'Class:ProjectChange/Stimulus:ev_reject' => 'Rejeter',
	'Class:ProjectChange/Stimulus:ev_reopen' => 'Ré-Ouvrir',
	'Class:ProjectChange+' => 'Change on project',

	'Class:lnkProjectChangeToWBS' => 'Lien Changement sur projet / WBS',
	'Class:lnkProjectChangeToWBS/Attribute:projectchange_id' => 'Changement sur projet',
	'Class:lnkProjectChangeToWBS/Attribute:wbs_id' => 'Livrables',
	'Class:lnkProjectChangeToWBS/Name' => '%1$s - %2$s',

	'Menu:MyProjectChange' => 'Mes changements sur projet',
	'Menu:MyProjectChange+' => 'Les changements sur projet qui me sont assignés',
	'Menu:NewProjectChange' => 'Nouveau changement sur projet',
	'Menu:ProjectChangeMenu'  =>  'Changement sur projet',
	'Menu:SearchProjectChange' => 'Rechercher des changements sur projet',
));

// WBS Class
Dict::Add('FR FR', 'French', 'Français', array(
    'Class:WBS/Attribute:projectchanges_list' => 'Changements sur projet',
    'Class:WBS/Attribute:risks_list' => 'Risques',
));
