<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'EN US', 'English', 'English', array (
		'Menu:Automatisme' => 'Automation',
		'Class:AutomatismePhysical' => 'Electrical Alimented Object',
		'Class:AutomatismePhysical+' => '',
		//'Class:AutomatismePhysical/Name' => '%2$s - %1$s - %3$s',
		'Class:AutomatismePhysical/Attribute:powerstart_id' => 'Power Alim',
		'Class:AutomatismePhysical/Attribute:powerstart_id+' => '',
		'Class:AutomatismePhysical/Attribute:powerstart_name' => 'Power Alim Name',
		'Class:AutomatismePhysical/Attribute:powerstart_name+' => '',
		'Class:AutomatismePhysical/Attribute:fqdn' => 'FQDN',
		'Class:AutomatismePhysical/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:AutomatismePhysical/Attribute:facilities_id' => 'Facilities Reference',
		'Class:AutomatismePhysical/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:BoitierGTC' => 'GTC data collector',
		'Class:BoitierGTC+' => '',
		//'Class:BoitierGTC/Name' => '%2$s - %1$s - %3$s',
		'Class:BoitierGTC/Attribute:softwareinstance_id' => 'GTC Server',
		'Class:BoitierGTC/Attribute:softwareinstance_id+' => '',
		'Class:BoitierGTC/Attribute:softwareinstance_name' => 'GTC Server name',
		'Class:BoitierGTC/Attribute:softwareinstance_name+' => '',
		'Class:BoitierGTC/Attribute:fqdn' => 'FQDN',
		'Class:BoitierGTC/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:BoitierGTC/Attribute:pdu_list' => 'PDU',
		'Class:BoitierGTC/Attribute:pdu_list+' => 'PDU connected to this GTC Data collector',
		'Class:PDU/Attribute:boitiergtc_id' => 'TDO data collector',
		'Class:PDU/Attribute:boitiergtc_name' => 'TDO data collector Name',
		'Class:PDU/Attribute:oid_tdo' => 'TDO data collector ID',
		'Class:PDU/Attribute:oid_tdo+' => 'ID/final OID for collects electrical data in TDO. Example 10 or 10.2',
		'Class:CameraVideo' => 'Video camera',
		'Class:CameraVideo+' => '',
		//'Class:CameraVideo/Name' => '%2$s - %1$s - %3$s',
		'Class:CameraVideo/Attribute:enregistreurcctv_id' => 'CCTV Recorder',
		'Class:CameraVideo/Attribute:enregistreurcctv_id+' => '',
		'Class:CameraVideo/Attribute:enregistreurcctv_name' => 'CCTV recorder\s name',
		'Class:CameraVideo/Attribute:enregistreurcctv_name+' => '',
		'Class:CameraVideo/Attribute:fqdn' => 'FQDN',
		'Class:CameraVideo/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:CentraleIncendie' => 'Fire Panel',
		'Class:CentraleIncendie+' => '',
		//'Class:CentraleIncendie/Name' => '%2$s - %1$s - %3$s',
		'Class:CentraleIncendie/Attribute:extinctionincendie_list' => 'Fire Extinguishers',
		'Class:CentraleIncendie/Attribute:extinctionincendie_list+' => 'Fire Extinguishers list',
		'Class:CentraleIncendie/Attribute:fqdn' => 'FQDN',
		'Class:CentraleIncendie/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:CentraleAlarme' => 'Central alarm',
		'Class:CentraleAlarme+' => '',
		//'Class:CentraleAlarme/Name' => '%2$s - %1$s - %3$s',
		'Class:CentraleAlarme/Attribute:fqdn' => 'FQDN',
		'Class:CentraleAlarme/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:CoffretControleur' => 'Access Controler Box',
		'Class:CoffretControleur+' => '',
		//'Class:CoffretControleur/Name' => '%2$s - %1$s - %3$s',
		'Class:CoffretControleur/Attribute:softwareinstance_id' => 'Winpack server',
		'Class:CoffretControleur/Attribute:softwareinstance_id+' => '',
		'Class:CoffretControleur/Attribute:softwareinstance_name' => 'Winpack server name',
		'Class:CoffretControleur/Attribute:softwareinstance_name+' => '',
		'Class:CoffretControleur/Attribute:fqdn' => 'FQDN',
		'Class:CoffretControleur/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:EnregistreurCCTV' => 'CCTV recoder',
		'Class:EnregistreurCCTV+' => '',
		//'Class:EnregistreurCCTV/Name' => '%2$s - %1$s - %3$s',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_id' => 'IVMS Server',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_id+' => '',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_name' => 'IVMS server name',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_name+' => '',
		'Class:EnregistreurCCTV/Attribute:cameravideo_list' => 'Video Cameras',
		'Class:EnregistreurCCTV/Attribute:cameravideo_list+' => 'Connected Video Cameras list',
		'Class:EnregistreurCCTV/Attribute:redundancy' => 'High availability',
		'Class:EnregistreurCCTV/Attribute:redundancy/disabled' => 'The CCTV recoder is up if all the video cameras are up',
		'Class:EnregistreurCCTV/Attribute:redundancy/count' => 'The CCTV recoder is up if at least %1$s video camera(s) is(are) up',
		'Class:EnregistreurCCTV/Attribute:redundancy/percent' => 'The CCTV recoder is up if at least %1$s %% of the video cameras are up',
		'Class:EnregistreurCCTV/Attribute:fqdn' => 'FQDN',
		'Class:EnregistreurCCTV/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:ExtinctionIncendie' => 'Fire Extinction',
		'Class:ExtinctionIncendie+' => '',
		//'Class:ExtinctionIncendie/Name' => '%2$s - %1$s - %3$s',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_id' => 'Fire Panel',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_id+' => '',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_name' => 'Fire Panel Name',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_name+' => '',
		'Class:ExtinctionIncendie/Attribute:fqdn' => 'FQDN',
		'Class:ExtinctionIncendie/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
) );
?>
