<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'FR FR', 'French', 'Français', array (
		'Menu:Automatisme' => 'Automatisme',
		'Class:AutomatismePhysical' => 'Objet d\'automatisme',
		'Class:AutomatismePhysical+' => '',
		'Class:AutomatismePhysical/Name' => '%2$s - %1$s - %3$s',
		'Class:AutomatismePhysical/Attribute:powerstart_id' => 'Arrivée électrique',
		'Class:AutomatismePhysical/Attribute:powerstart_id+' => '',
		'Class:AutomatismePhysical/Attribute:powerstart_name' => 'Nom Arrivée électrique',
		'Class:AutomatismePhysical/Attribute:powerstart_name+' => '',
		'Class:AutomatismePhysical/Attribute:fqdn' => 'FQDN',
		'Class:AutomatismePhysical/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:AutomatismePhysical/Attribute:facilities_id' => 'Référence Facilities',
		'Class:AutomatismePhysical/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:BoitierGTC' => 'Boitier GTC',
		'Class:BoitierGTC+' => '',
		'Class:BoitierGTC/Name' => '%2$s - %1$s - %3$s',
		'Class:BoitierGTC/Attribute:softwareinstance_id' => 'Serveur GTC',
		'Class:BoitierGTC/Attribute:softwareinstance_id+' => '',
		'Class:BoitierGTC/Attribute:softwareinstance_name' => 'Nom du serveur GTC',
		'Class:BoitierGTC/Attribute:softwareinstance_name+' => '',
		'Class:BoitierGTC/Attribute:fqdn' => 'FQDN',
		'Class:BoitierGTC/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:BoitierGTC/Attribute:pdu_list' => 'PDU',
		'Class:BoitierGTC/Attribute:pdu_list+' => 'PDU connecté à ce Boitier GTC',
		'Class:PDU/Attribute:boitiergtc_id' => 'Boitier TDO',
		'Class:PDU/Attribute:boitiergtc_name' => 'Nom du Boitier TDO',
		'Class:PDU/Attribute:oid_tdo' => 'ID du TDO à collecter',
		'Class:PDU/Attribute:oid_tdo+' => 'ID ou OID à collecter dans le TDO. Exemple : 10 ou 10.2',
		'Class:CameraVideo' => 'Caméra Vidéo',
		'Class:CameraVideo+' => '',
		'Class:CameraVideo/Name' => '%2$s - %1$s - %3$s',
		'Class:CameraVideo/Attribute:enregistreurcctv_id' => 'Enregistreur CCTV',
		'Class:CameraVideo/Attribute:enregistreurcctv_id+' => '',
		'Class:CameraVideo/Attribute:enregistreurcctv_name' => 'Nom de l\'Enregistreur CCTV',
		'Class:CameraVideo/Attribute:enregistreurcctv_name+' => '',
		'Class:CameraVideo/Attribute:fqdn' => 'FQDN',
		'Class:CameraVideo/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:CentraleIncendie' => 'Centrale Incendie',
		'Class:CentraleIncendie+' => '',
		'Class:CentraleIncendie/Name' => '%2$s - %1$s - %3$s',
		'Class:CentraleIncendie/Attribute:extinctionincendie_list' => 'Extincteurs Incendie',
		'Class:CentraleIncendie/Attribute:extinctionincendie_list+' => 'Liste des Extincteurs Incendie connectés',
		'Class:CentraleIncendie/Attribute:fqdn' => 'FQDN',
		'Class:CentraleIncendie/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:CentraleAlarme' => 'Centrale d\'Alarme',
		'Class:CentraleAlarme+' => '',
		'Class:CentraleAlarme/Name' => '%2$s - %1$s - %3$s',
		'Class:CentraleAlarme/Attribute:fqdn' => 'FQDN',
		'Class:CentraleAlarme/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:CoffretControleur' => 'Coffret contrôleur d\'accés',
		'Class:CoffretControleur+' => '',
		'Class:CoffretControleur/Name' => '%2$s - %1$s - %3$s',
		'Class:CoffretControleur/Attribute:softwareinstance_id' => 'Serveur Winpack',
		'Class:CoffretControleur/Attribute:softwareinstance_id+' => '',
		'Class:CoffretControleur/Attribute:softwareinstance_name' => 'Nom du serveur Winpack',
		'Class:CoffretControleur/Attribute:softwareinstance_name+' => '',
		'Class:CoffretControleur/Attribute:fqdn' => 'FQDN',
		'Class:CoffretControleur/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:EnregistreurCCTV' => 'Enregistreur CCTV',
		'Class:EnregistreurCCTV+' => '',
		'Class:EnregistreurCCTV/Name' => '%2$s - %1$s - %3$s',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_id' => 'Serveur IVMS',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_id+' => '',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_name' => 'Nom du serveur IVMS',
		'Class:EnregistreurCCTV/Attribute:softwareinstance_name+' => '',
		'Class:EnregistreurCCTV/Attribute:cameravideo_list' => 'Caméras Vidéo',
		'Class:EnregistreurCCTV/Attribute:cameravideo_list+' => 'Liste des Caméras Vidéo connectées',
		'Class:EnregistreurCCTV/Attribute:redundancy' => 'Haute disponibilité',
		'Class:EnregistreurCCTV/Attribute:redundancy/disabled' => 'L\'enregistreur CCTV est opérationnel si toutes les caméras vidéo qui le composent sont opérationnels',
		'Class:EnregistreurCCTV/Attribute:redundancy/count' => 'Nombre minimal de caméras vidéo pour que l\'enregistreur CCTV soit opérationnel : %1$s',
		'Class:EnregistreurCCTV/Attribute:redundancy/percent' => 'Pourcentage minimal de caméras vidéo pour que l\'enregistreur CCTV soit opérationnel : %1$s %%',
		'Class:EnregistreurCCTV/Attribute:fqdn' => 'FQDN',
		'Class:EnregistreurCCTV/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:ExtinctionIncendie' => 'Extinction d\'Incendie',
		'Class:ExtinctionIncendie+' => '',
		'Class:ExtinctionIncendie/Name' => '%2$s - %1$s - %3$s',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_id' => 'Centrale Incendie',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_id+' => '',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_name' => 'Nom de la Centrale Incendie',
		'Class:ExtinctionIncendie/Attribute:centraleincendie_name+' => '',
		'Class:ExtinctionIncendie/Attribute:fqdn' => 'FQDN',
		'Class:ExtinctionIncendie/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
) );
?>
