<?php

Dict::Add('EN US', 'English', 'English', array(
	'Class:Rack/Attribute:contracted_power' => 'Customer contracted power (kVA)',
	'Class:Rack/Attribute:contracted_power+' => 'Customer contracted power on this Rack.',
	'Class:Rack/Attribute:installed_power' => 'Rack Installed power (kVA)',
	'Class:Rack/Attribute:installed_power+' => 'Physical power privided to the Rack.',
	'Class:Rack/Attribute:power_reading_value' => 'Power reading (kVA)',
	'Class:Rack/Attribute:power_reading_value+' => 'Declared bu User. Power read on measurement on electric collector.',
	'Class:Rack/Attribute:power_reading_date' => 'Power reading date',
	'Class:Rack/Attribute:power_reading_date+' => 'Reading date for power read value',
	'Class:Rack/Attribute:power_contracted_usage' => 'Power contrated usage',
	'Class:Rack/Attribute:power_contracted_usage+' => 'Usage of the contracted power. Calculate between "Customer contracted power" and "Power reading".',
	'Class:Rack/Attribute:power_installed_usage' => 'Power installed usage',
	'Class:Rack/Attribute:power_installed_usage+' => 'Usage of the installed power. Calculate between "Rack Installed power" and "Power reading".',
	'Class:CustomerContract/Attribute:contracted_power' => 'Customer contracted power (kVA)',
	'Class:CustomerContract/Attribute:contracted_power+' => 'Declared bu User. Customer contracted power for this contract.',
	'Class:CustomerContract/Attribute:installed_power' => 'Rack Installed power (kVA)',
	'Class:CustomerContract/Attribute:installed_power+' => 'Calculated. Customer power declared in "Customer contracted power" on each Rack.',
	'Class:CustomerContract/Attribute:power_reading_value' => 'Power reading (kVA)',
	'Class:CustomerContract/Attribute:power_reading_value+' => 'Calculated. Power read on all Customer\'s Rack.',
	'Class:CustomerContract/Attribute:power_reading_date' => 'Power reading date',
	'Class:CustomerContract/Attribute:power_reading_date+' => 'Reading date for power read value',
	'Class:CustomerContract/Attribute:power_contracted_usage' => 'Power contrated usage',
	'Class:CustomerContract/Attribute:power_contracted_usage+' => 'Usage of the contracted power. Calculate between "Customer contracted power" and "Power reading".',
	'Class:CustomerContract/Attribute:power_installed_usage' => 'Power installed usage',
	'Class:CustomerContract/Attribute:power_installed_usage+' => 'Usage of the installed power. Calculate between "Rack Installed power" and "Power reading".',
	'Class:Location/Attribute:contracted_power' => 'Location contracted power (kVA)',
	'Class:Location/Attribute:contracted_power+' => 'Calculated. Location power declared in "Customer contracted power" on each Rack.',
	'Class:Location/Attribute:installed_power' => 'Rack Installed power (kVA)',
	'Class:Location/Attribute:installed_power+' => 'Declared bu User. Location\'s power capacity.',
	'Class:Location/Attribute:power_reading_value' => 'Power reading (kVA)',
	'Class:Location/Attribute:power_reading_value+' => 'Calculated. Power read on all Location\'s Rack.',
	'Class:Location/Attribute:power_reading_date' => 'Power reading date',
	'Class:Location/Attribute:power_reading_date+' => 'Reading date for power read value',
	'Class:Location/Attribute:power_contracted_usage' => 'Power contrated usage',
	'Class:Location/Attribute:power_contracted_usage+' => 'Usage of the contracted power. Calculate between "Customer contracted power" and "Power reading".',
	'Class:Location/Attribute:power_installed_usage' => 'Power installed usage',
	'Class:Location/Attribute:power_installed_usage+' => 'Usage of the installed power. Calculate between "Rack Installed power" and "Power reading".',
));
