<?php

Dict::Add('FR FR', 'French', 'Français', array(
	'Class:Rack/Attribute:contracted_power' => 'Puissance contractuelle (kVA)',
	'Class:Rack/Attribute:contracted_power+' => 'Déclaration manuelle. Puissance contractuelle vendue au client.',
	'Class:Rack/Attribute:installed_power' => 'Puissance installée (kVA)',
	'Class:Rack/Attribute:installed_power+' => 'Déclaration manuelle. Puissance physique installée dans le Rack.',
	'Class:Rack/Attribute:power_reading_value' => 'Puissance lue (kVA)',
	'Class:Rack/Attribute:power_reading_value+' => 'Déclaration manuelle. Puissance mesurée dans le Rack par un outil de mesure externe.',
	'Class:Rack/Attribute:power_reading_date' => 'Date de la puissance lue',
	'Class:Rack/Attribute:power_reading_date+' => 'Date Lecture puissance lue',
	'Class:Rack/Attribute:power_contracted_usage' => 'Util. Puissance contractuelle',
	'Class:Rack/Attribute:power_contracted_usage+' => 'Calculée. Utilisation de la puissance contractuelle, Calcul fait entre "Puissance contractuelle (kVA)" et "Puissance lue (kVA)".',
	'Class:Rack/Attribute:power_installed_usage' => 'Util. puissance installée',
	'Class:Rack/Attribute:power_installed_usage+' => 'Calculée. Utilisation de la puissance installée, Calcul fait entre "Puissance installée (kVA)" et "Puissance lue (kVA)".',
	'Class:CustomerContract/Attribute:contracted_power' => 'Puissance contractuelle (kVA)',
	'Class:CustomerContract/Attribute:contracted_power+' => 'Déclaration manuelle. Puissance contractuelle vendue au client. Tous sites confondus.',
	'Class:CustomerContract/Attribute:installed_power' => 'Puissance installée (kVA)',
	'Class:CustomerContract/Attribute:installed_power+' => 'Calculée. Somme des puissances contractuelles des Racks installées pour ce client. Tous sites confondus.',
	'Class:CustomerContract/Attribute:power_reading_value' => 'Puissance lue (kVA)',
	'Class:CustomerContract/Attribute:power_reading_value+' => 'Calculée. Somme des puissances mesurées dans les Racks pour ce client.',
	'Class:CustomerContract/Attribute:power_reading_date' => 'Date de la puissance lue',
	'Class:CustomerContract/Attribute:power_reading_date+' => 'Date de la puissance lue',
	'Class:CustomerContract/Attribute:power_contracted_usage' => 'Util. Puissance contractuelle',
	'Class:CustomerContract/Attribute:power_contracted_usage+' => 'Calculée. Utilisation de la puissance contractuelle, Calcul fait entre "Puissance contractuelle (kVA)" et "Puissance lue (kVA)".',
	'Class:CustomerContract/Attribute:power_installed_usage' => 'Util. puissance installée',
	'Class:CustomerContract/Attribute:power_installed_usage+' => 'Calculée. Utilisation de la puissance installée, Calcul fait entre "Puissance installée (kVA)" et "Puissance lue (kVA)".',
	'Class:Location/Attribute:contracted_power' => 'Puissance contractuelle (kVA)',
	'Class:Location/Attribute:contracted_power+' => 'Calculée. Somme des puissances contractuelles des Racks installées pour ce lieux. Tous sous-lieux confondus.',
	'Class:Location/Attribute:installed_power' => 'Puissance installée (kVA)',
	'Class:Location/Attribute:installed_power+' => 'Déclaration manuelle. Puissance IT installée dans ce lieu. Tous sous-lieux confondus.',
	'Class:Location/Attribute:power_reading_value' => 'Puissance lue (kVA)',
	'Class:Location/Attribute:power_reading_value+' => 'Calculée. Somme des puissances mesurées dans les Racks pour ce lieux et sous-lieux.',
	'Class:Location/Attribute:power_reading_date' => 'Date de la puissance lue',
	'Class:Location/Attribute:power_reading_date+' => 'Date de la puissance lue',
	'Class:Location/Attribute:power_contracted_usage' => 'Util. Puissance contractuelle',
	'Class:Location/Attribute:power_contracted_usage+' => 'Calculée. Utilisation de la puissance contractuelle, Calcul fait entre "Puissance contractuelle (kVA)" et "Puissance lue (kVA)".',
	'Class:Location/Attribute:power_installed_usage' => 'Util. puissance installée',
	'Class:Location/Attribute:power_installed_usage+' => 'Calculée. Utilisation de la puissance installée, Calcul fait entre "Puissance installée (kVA)" et "Puissance lue (kVA)".',
));
