<?php

Dict::Add('FR FR', 'French', 'Français', array(
	'Class:AuthTokenClient' => 'Client Auth Token',
	'Class:AuthTokenClient+' => 'Configure Auth connexion basée sur un Token.',
	'Class:AuthTokenClient/Attribute:name' => 'Nom',
	'Class:AuthTokenClient/Attribute:name+' => 'Nom du token.',
	'Class:AuthTokenClient/Attribute:username' => 'Nom d\'utilisateur',
	'Class:AuthTokenClient/Attribute:username+' => 'Login de l\'utilisateur de connexion',
	'Class:AuthTokenClient/Attribute:password' => 'Mot de passe',
	'Class:AuthTokenClient/Attribute:password+' => 'Mot de passe de connexion for logon',
	'Class:AuthTokenClient/Attribute:description' => 'Description',
	'Class:AuthTokenClient/Attribute:description+' => 'Description de l\'objet',
	'Class:AuthTokenClient/Attribute:base_url' => 'URL du serveur',
	'Class:AuthTokenClient/Attribute:base_url+' => '',
	'Class:AuthTokenClient/Attribute:access_token' => 'Token d\'accés',
	'Class:AuthTokenClient/Attribute:access_token+' => 'Token fournit par le serveur pour conserver la connexion',
	'Class:AuthTokenClient/Attribute:access_token_expiration' => 'Date d\'expiration du token',
	'Class:AuthTokenClient/Attribute:access_token_expiration+' => '',
	'Class:AuthTokenClient/Attribute:access_token_expiration' => 'Date d\'expiration du token',
	'AuthTokenClient:baseinfo' => 'Informations de base',
	'AuthTokenClient:idp_info' => 'Informations de connexion',
	'Menu:AuthTokenClient' => 'Client Auth Token',
	'Menu:AuthTokenClient+' => 'Configure Auth connexion basée sur un Token.',
));
