<?php
// PHP Data Model definition file
// WARNING - WARNING - WARNING
// DO NOT EDIT THIS FILE (unless you know what you are doing)
//
// If you use supply a datamodel.xxxx.xml file with your module
// the this file WILL BE overwritten by the compilation of the
// module (during the setup) if the datamodel.xxxx.xml file
// contains the definition of new classes or menus.
//
// The recommended way to define new classes (for iTop 2.0) is via the XML definition.
// This file remains in the module's template only for the cases where there is:
// - either no new class or menu defined in the XML file
// - or no XML file at all supplied by the module
class ManageEscalation implements iMetricComputer
{
	public static function GetDescription()
	{
		return "Number of waiting days before escalate to management";
	}
	
	public function ComputeMetric($oObject)
	{
		$iDelay = null; /* returning 'null' means 'no goal' */
		// If there is a planned_date attribute and it has a non-empty value
		if (MetaModel::IsValidAttCode(get_class($oObject), 'management_escalation_day') && (!empty($oObject->Get('management_escalation_day'))))
		{
			$oDiff=$oObject->Get('management_escalation_day')*24*3600;
			$oActualDate = new DateTime();
			$oLastUpdate = new DateTime($oObject->Get('last_update'));
			// Calculate the delay between now and the last_update
			$iDelayLastUpdate = $oActualDate->format('U') - $oLastUpdate->format('U');
			// If the difference between last update and now is up to management_escalation_day
			$iDiff=$iDelayLastUpdate-$oDiff;
			$iDelay = ($iDiff < 0) ? 0 : 100;
		}
		return $iDelay;
	}
}