<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('EN US', 'English', 'English', array(
		// Dictionary entries go here
		'Menu:Backup' => 'Backup',
		'Class:BaseSauvegarde' => 'Backup Based',
		'Class:BaseSauvegarde/Attribute:name' => 'Name',
		'Class:BaseSauvegarde/Attribute:org_id' => 'Organization',
		'Class:BaseSauvegarde/Attribute:organization_uniq_id' => 'Organization Uniq ID',
		'Class:BaseSauvegarde/Attribute:functionalcis_list' => 'CIs',
		'Class:BaseSauvegarde/Attribute:functionalcis_list+' => '',
		'Class:BaseSauvegarde/Attribute:server_id' => 'Backup Server',
		'Class:BaseSauvegarde/Attribute:server_id+' => 'Server (VM) managing this backup',
		'Class:BaseSauvegarde/Attribute:windows_enable' => 'Backup window ?',
		'Class:BaseSauvegarde/Attribute:windows_enable/Value:yes' => 'Yes',
		'Class:BaseSauvegarde/Attribute:windows_enable/Value:no' => 'No',
		'Class:BaseSauvegarde/Attribute:windows_fromhours' => 'Starting window',
		'Class:BaseSauvegarde/Attribute:windows_tohours' => 'Ending window',
		'Class:BaseSauvegarde/Attribute:at_time' => 'Backup scheduling',
		'Class:BaseSauvegarde/Attribute:at_time+' => 'Backup scheduling format : To define the time you can provide concrete values for minute (m), hour (h), day of month (dom), month (mon), and day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat or use \'*\'',
		'Class:BaseSauvegarde/Attribute:scaleoutrepository_id' => 'Scale Out Repository',
		'Class:BaseRulesSauvegarde/Attribute:retention_type' => 'Retention Type',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:restorepoint' => 'Restore Point',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:day' => 'Day',
		'Class:BaseRulesSauvegarde/Attribute:nbretention' => 'Rentention number',
		'Class:BaseRulesSauvegarde/Attribute:algorythme' => 'Backup type',
		'Class:BaseRulesSauvegarde/Attribute:algorythme/Value:incremental' => 'Incremental',
		'Class:BaseRulesSauvegarde/Attribute:algorythme/Value:decremental' => 'Decremental',
		'Class:BaseRulesSauvegarde/Attribute:algorythme/Value:differential' => 'Differential',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_enable' => 'Backup Full ?',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_enable/Value:yes' => 'Yes',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_enable/Value:no' => 'No',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_day' => 'Bakup Full Day',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:sunday' => 'Sunday',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:monday' => 'Monday',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:tuesday' => 'Tuesday',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:wednesday' => 'Wednesday',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:thursday' => 'Thursday',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:friday' => 'Friday',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:saturday' => 'Saturday',
		'Class:BaseRulesSauvegarde/Attribute:repository_id' => 'Storage',
		'Class:BaseRulesSauvegarde/Attribute:repository_id+' => 'Destination storage',
		'Class:Backup' => 'Backup',
		'BaseSauvegarde:baseinfo'=>'General information',
		'BaseSauvegarde:window'=>'Backup window',
		'Backup:details'=>'Retention management',
		'Replication:details'=>'Replication management',
		'Class:Replication' => 'Replication',
		'Class:Replication/Attribute:postpend' => 'Postpend to VM\'s name',
		'Class:Replication/Attribute:vcenter_id' => 'Destination Vcenter',
		'Class:Replication/Attribute:virtualhost_id' => 'Destination Cluster or Hypervisor',
		'Class:Replication/Attribute:vmfolder' => 'Destination Folder',
		'Class:Replication/Attribute:logicalvolume_id' => 'Destination Datastore',
		'Class:BackupCopy' => 'Backup Copy',
		'Class:VMCopy' => 'VM Copy',
		'Class:FileCopy' => 'File Copy',
		'Class:FileCopy/Attribute:vmfolder' => 'Folder to save',
		'Class:lnkFunctionalCIToBackup' => 'Link Functional CI To Backup',
		'Class:lnkFunctionalCIToBackup/Attribute:backup_id' => 'Backup',
		'Class:lnkFunctionalCIToBackup/Attribute:functionalci_id' => 'CI',
		'Class:FunctionalCI/Attribute:backups_list' => 'Backups list',
		'Class:FunctionalCI/Attribute:backups_list+' => 'Backups used by this CI',
		'CI:Overview:Sauvegarde' => 'Backups',
		'CI:Overview:Sauvegarde:subtitle' => 'List of Backups for this CI',
		'Class:BackupCopy/Attribute:server_id' => 'Source storage',
		'Class:BackupCopy/Attribute:server_id+' => 'Source storage (VM) contains backups',
		'Class:ScaleOutRepository' => 'Scale Out Repository',
		'Class:ScaleOutRepository/Attribute:name' => 'Name',
		'Class:ScaleOutRepository/Attribute:sauvegardes_list' => 'Backup List',
));
?>
