<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'FR FR', 'French', 'Français', array (
		// Dictionary entries go here
		'Menu:Sauvegarde' => 'Sauvegarde',
		'Class:BaseSauvegarde' => 'Base des Backups',
		'Class:BaseSauvegarde/Attribute:name' => 'Nom',
		'Class:BaseSauvegarde/Attribute:org_id' => 'Organisation',
		'Class:BaseSauvegarde/Attribute:organization_uniq_id' => 'ID unique de l\'organisation',
		'Class:BaseSauvegarde/Attribute:functionalcis_list' => 'CIs',
		'Class:BaseSauvegarde/Attribute:functionalcis_list+' => '',
		'Class:BaseSauvegarde/Attribute:server_id' => 'Serveur de Backup',
		'Class:BaseSauvegarde/Attribute:server_id+' => 'Serveur (VM) qui gère le backup',
		'Class:BaseSauvegarde/Attribute:windows_enable' => 'Fenêtre de traitement ?',
		'Class:BaseSauvegarde/Attribute:windows_enable/Value:yes' => 'Oui',
		'Class:BaseSauvegarde/Attribute:windows_enable/Value:no' => 'Non',
		'Class:BaseSauvegarde/Attribute:windows_fromhours' => 'Début de la fenêtre',
		'Class:BaseSauvegarde/Attribute:windows_tohours' => 'Fin de la fenêtre',
		'Class:BaseSauvegarde/Attribute:at_time' => 'Planification',
		'Class:BaseSauvegarde/Attribute:at_time+' => 'Planification de traitement au format suivant : Pour définir la planification, il faut fournir les minutes (m), les heures (h), jour de mois (de 1 à 31), le mois (de 1 à 12) et le jour de la semaine (0 - 6) (Dimanche=0 or 7). Vous pouvez utiliser \'*\' pour chaque valeur',
		'Class:BaseSauvegarde/Attribute:scaleoutrepository_id' => 'Dossier Scale Out',
		'Class:BaseRulesSauvegarde/Attribute:retention_type' => 'Type de rétention',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:restorepoint' => 'Point de restauration',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:day' => 'Jour',
		'Class:BaseRulesSauvegarde/Attribute:nbretention' => 'Nombre de rétention',
		'Class:BaseRulesSauvegarde/Attribute:algorythme' => 'Type de Sauvegarde',
		'Class:BaseRulesSauvegarde/Attribute:algorythme/Value:incremental' => 'Incrémentale',
		'Class:BaseRulesSauvegarde/Attribute:algorythme/Value:decremental' => 'Décrémentale',
		'Class:BaseRulesSauvegarde/Attribute:algorythme/Value:differential' => 'Différentiel',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_enable' => 'Sauvegarde Full ?',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_enable/Value:yes' => 'Oui',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_enable/Value:no' => 'Non',
		'Class:BaseRulesSauvegarde/Attribute:fullbackup_day' => 'Jour du backup Full',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:sunday' => 'Dimanche',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:monday' => 'Lundi',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:tuesday' => 'Mardi',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:wednesday' => 'Mercredi',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:thursday' => 'Jeudi',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:friday' => 'Vendredi',
		'Class:BaseRulesSauvegarde/Attribute:retention_type/Value:saturday' => 'Samedi',
		'Class:BaseRulesSauvegarde/Attribute:repository_id' => 'Stockage',
		'Class:BaseRulesSauvegarde/Attribute:repository_id+' => 'Stockage de destination',
		'Class:Backup' => 'Sauvegarde',
		'BaseSauvegarde:baseinfo'=>'Informations générales',
		'BaseSauvegarde:window'=>'Fenêtre de sauvegarde',
		'Backup:details'=>'Gestion de la rétention',
		'Replication:details'=>'Gestion de la réplication',
		'Class:Replication' => 'Réplication',
		'Class:Replication/Attribute:postpend' => 'Ajout au nom de la VM',
		'Class:Replication/Attribute:vcenter_id' => 'Vcenter de destination',
		'Class:Replication/Attribute:virtualhost_id' => 'Cluster ou Hyperviseur de destination',
		'Class:Replication/Attribute:vmfolder' => 'Dossier de destination',
		'Class:Replication/Attribute:logicalvolume_id' => 'Datastore de destination',
		'Class:BackupCopy' => 'Backup Copy',
		'Class:VMCopy' => 'VM Copy',
		'Class:FileCopy' => 'File Copy',
		'Class:FileCopy/Attribute:vmfolder' => 'Dossier à sauvegarder',
		'Class:lnkFunctionalCIToBackup/Name' => 'Lien Functional CI Vers Backup',
		'Class:lnkFunctionalCIToBackup/Attribute:backup_id' => 'Sauvegarde',
		'Class:lnkFunctionalCIToBackup/Attribute:functionalci_id' => 'CI',
		'Class:FunctionalCI/Attribute:backups_list' => 'Liste Sauvegardes',
		'Class:FunctionalCI/Attribute:backups_list+' => 'Liste des Sauvegardes pour ce CI',
		'CI:Overview:Sauvegarde' => 'Sauvegardes',
		'CI:Overview:Sauvegarde:subtitle' => 'Liste des Sauvegardes pour ce CI',
		'Class:BackupCopy/Attribute:server_id' => 'Stockage source',
		'Class:BackupCopy/Attribute:server_id+' => 'Serveur de stockage (VM) qui contient le backup',
		'Class:ScaleOutRepository' => 'Dossier Scale Out',
		'Class:ScaleOutRepository/Attribute:name' => 'Nom',
		'Class:ScaleOutRepository/Attribute:sauvegardes_list' => 'Liste des sauvegardes',
) );
?>
