<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'EN US', 'English', 'English', array (
		'Menu:Electricity' => 'Electricity',
		'Class:Tank/Attribute:fqdn' => 'FQDN',
		'Class:Tank/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerDistributionUnit' => 'Electrical distribution Unit',
		'Class:PowerDistributionUnit+' => '',
		//'Class:PowerDistributionUnit/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerDistributionUnit/Attribute:powerA_id' => 'Main Source Elect Board',
		'Class:PowerDistributionUnit/Attribute:powerA_id+' => 'Main electrical board',
		'Class:PowerDistributionUnit/Attribute:powerA_name' => 'Main Source Elect Board name',
		'Class:PowerDistributionUnit/Attribute:powerA_name+' => 'Main electrical board name',
		'Class:PowerDistributionUnit/Attribute:powerB_id' => 'Secondary Power source',
		'Class:PowerDistributionUnit/Attribute:powerB_id+' => 'Secondary Power source is optional',
		'Class:PowerDistributionUnit/Attribute:powerB_name' => 'Secondary Power source',
		'Class:PowerDistributionUnit/Attribute:powerB_name+' => 'Secondary Power source is optional',
		'Class:PowerDistributionUnit/Attribute:pdus_list' => 'PDUs List',
		'Class:PowerDistributionUnit/Attribute:pdus_list+' => '',
		'Class:PowerDistributionUnit/Attribute:powerbreakers_list' => 'Circuit-Breakers List',
		'Class:PowerDistributionUnit/Attribute:powerbreakers_list+' => '',
		'Class:PowerDistributionUnit/Attribute:powercircuits_list' => 'Electrical Circuits List',
		'Class:PowerDistributionUnit/Attribute:powercircuits_list+' => '',
		'Class:PowerDistributionUnit/Attribute:powerfaultdetectionrelays_list' => 'Fault-Detecting Relays List',
		'Class:PowerDistributionUnit/Attribute:powerfaultdetectionrelays_list+' => '',
		'Class:PowerDistributionUnit/Attribute:fqdn' => 'FQDN',
		'Class:PowerDistributionUnit/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerDistributionUnit/Attribute:redundancy' => 'High availability',
		'Class:PowerDistributionUnit/Attribute:redundancy/disabled' => 'Electrical distribution Unit is up if all power sources are up',
		'Class:PowerDistributionUnit/Attribute:redundancy/count' => 'Electrical distribution Unit is up if at least %1$s power sources are up',
		'Class:PowerDistributionUnit/Attribute:redundancy/percent' => 'Electrical distribution Unit is up if at least %1$s %% of power sources are up',
		'Class:PowerBreaker' => 'Circuit-Breaker',
		'Class:PowerBreaker+' => '',
		//'Class:PowerBreaker/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id' => 'Electrical distribution Unit',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id' => 'Electrical distribution Unit name',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerBreaker/Attribute:pdus_list' => 'PDUs List',
		'Class:PowerBreaker/Attribute:pdus_list+' => '',
		'Class:PowerFaultDetectionRelay' => 'Fault-Detecting Relay',
		'Class:PowerFaultDetectionRelay+' => '',
		//'Class:PowerFaultDetectionRelay/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id' => 'Electrical distribution Unit',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id' => 'Electrical distribution Unit name',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerFaultDetectionRelay/Attribute:powerbreakers_list' => 'Circuit-Breakers List',
		'Class:PowerFaultDetectionRelay/Attribute:powerbreakers_list+' => '',
		
		'Class:FootPrint' => 'FootPrint',
		'Class:FootPrint+' => '',
		'Class:FootPrint/Attribute:length' => 'Length',
		'Class:FootPrint/Attribute:width' => 'Witdh',
		'Class:FootPrint/Attribute:powercircuits_list' => 'Electrical Circuits',
		'Class:FootPrint/Attribute:powercircuits_list+' => 'Electrical circuits under the footprint',
		
		'Class:PowerCircuit' => 'Electrical Circuit',
		'Class:PowerCircuit+' => '',
		'Class:PowerCircuit/Attribute:power_usage' => 'Power max  (kVA)',
		'Class:PowerCircuit/Attribute:power_usage+' => 'Max Power available on this circuit',
		'Class:PowerCircuit/Attribute:type_phase' => 'Circuit Type',
		'Class:PowerCircuit/Attribute:type_phase/Value:monophase' => 'Single-Phase',
		'Class:PowerCircuit/Attribute:type_phase/Value:triphase' => 'Three-Phase',
		
		'Class:lnkFootPrintToPowerCircuit' => 'LNK FootPrint to Electrical Circuit',
		'Class:lnkFootPrintToPowerCircuit+' => '',
		'Class:lnkFootPrintToPowerCircuit/Attribute:footprint_id' => 'FootPrint',
		'Class:lnkFootPrintToPowerCircuit/Attribute:powercircuit_id' => 'Electrical Circuit',
		
		'Class:Rack/Attribute:footprint_id' => 'FootPrint',
		'Class:Rack/Attribute:footprint_id+' => 'FootPrint where the Rack is put on',
		'Class:Rack/Attribute:footprint_name' => 'FootPrint',
		
		'Class:PowerGeneralBoard' => 'Main Electrical Board',
		'Class:PowerGeneralBoard+' => '',
		//'Class:PowerGeneralBoard/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerGeneralBoard/Attribute:powersources_list' => 'Power sources list',
		'Class:PowerGeneralBoard/Attribute:powersources_list+' => 'Power sources list',
		'Class:PowerGeneralBoard/Attribute:fqdn' => 'FQDN',
		'Class:PowerGeneralBoard/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerGeneralBoard/Attribute:redundancy' => 'High availability',
		'Class:PowerGeneralBoard/Attribute:redundancy/disabled' => 'The Main Electrical Board is up if all the UPS are up',
		'Class:PowerGeneralBoard/Attribute:redundancy/count' => 'The Main Electrical Board is up if at least %1$s UPSs are up',
		'Class:PowerGeneralBoard/Attribute:redundancy/percent' => 'The Main Electrical Board is up if at least %1$s %% of UPSs are up',
		'Class:Tank' => 'Tank',
		'Class:Tank+' => '',
		//'Class:Tank/Name' => '%2$s.%3$s - %1$s',
		'Class:Tank/Attribute:groupeelectro_id' => 'Generator',
		'Class:Tank/Attribute:groupeelectro_id+' => '',
		'Class:Tank/Attribute:groupeelectro_name' => 'Generator name',
		'Class:Tank/Attribute:groupeelectro_name+' => '',
		'Class:Tank/Attribute:fqdn' => 'FQDN',
		'Class:Tank/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerGenerator' => 'Generator',
		'Class:PowerGenerator+' => '',
		//'Class:PowerGenerator/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerGenerator/Attribute:fqdn' => 'FQDN',
		'Class:PowerGenerator/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerSourceInverter' => 'Source Inverter',
		'Class:PowerSourceInverter+' => '',
		//'Class:PowerSourceInverter/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerSourceInverter/Attribute:powerA_id' => 'PowerA source',
		'Class:PowerSourceInverter/Attribute:powerA_id+' => '',
		'Class:PowerSourceInverter/Attribute:powerA_name' => 'PowerA source name',
		'Class:PowerSourceInverter/Attribute:powerA_name+' => '',
		'Class:PowerSourceInverter/Attribute:powerB_id' => 'PowerB source',
		'Class:PowerSourceInverter/Attribute:powerB_id+' => '',
		'Class:PowerSourceInverter/Attribute:powerB_name' => 'PowerB source name',
		'Class:PowerSourceInverter/Attribute:powerB_name+' => '',
		'Class:PowerSourceInverter/Attribute:redundancy' => 'Redundancy',
		'Class:PowerSourceInverter/Attribute:redundancy/count' => 'The device is up if at least one power connection (A or B) is up',
		'Class:PowerSourceInverter/Attribute:toggletype' => 'Toggle Method',
		'Class:PowerSourceInverter/Attribute:toggletype/Value:automatic' => 'Automatic',
		'Class:PowerSourceInverter/Attribute:toggletype/Value:manual' => 'Manual',
		'Class:UPS' => 'UPS',
		'Class:UPS+' => '',
		//'Class:UPS/Name' => '%2$s.%3$s - %1$s',
		'Class:UPS/Attribute:powergeneralboard_list' => 'List of Main electrical board',
		'Class:UPS/Attribute:powergeneralboard_list+' => 'List of Main electrical board Connected to this distribution box',
		'Class:UPS/Attribute:fqdn' => 'FQDN',
		'Class:UPS/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerTransform' => 'Electrical transformer',
		'Class:PowerTransform+' => '',
		//'Class:PowerTransform/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerTransform/Attribute:fqdn' => 'FQDN',
		'Class:PowerTransform/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_id' => 'Electrical source',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_id+' => 'Electrical source component',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_name' => 'Electrical source',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_name+' => 'Electrical source component',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_id' => 'Electrical destination',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_id+' => 'Component consuming electrical source',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_name' => 'Electrical destination',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_name+' => 'Component consuming electrical source',
		'Class:PowerSource/Attribute:Transfos_list' => 'Electrical transformers',
		'Class:PowerSource/Attribute:Transfos_list+' => '',
		'Class:PowerConnection/Attribute:facilities_id' => 'Facilities Reference',
		'Class:PowerConnection/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:PowerConnection/Attribute:powerstart_id' => 'Power source',
		'Class:PowerConnection/Attribute:powerstart_id+' => '',
		'Class:PowerConnection/Attribute:powerstart_name' => 'Power source name',
		'Class:PowerConnection/Attribute:powerstart_name+' => '',
		'Class:HVCell' => 'High Voltage Cell',
		'Class:HVCell+' => '',
		//'Class:HVCell/Name' => '%2$s.%3$s - %1$s',
		'Class:Battery' => 'Battery',
		'Class:Battery+' => '',
		//'Class:Battery/Name' => '%2$s.%3$s - %1$s',
		'Class:Battery/Attribute:powerconsumer_id' => 'Power Consumer',
		'Class:Battery/Attribute:powerconsumer_id+' => '',
		'Class:Battery/Attribute:powerconsumer_name' => 'Power Consumer Name',
		'Class:Battery/Attribute:powerconsumer_name+' => '',
				
		'Class:PDU' => 'Rack Power Distribution Unit',
		'Class:PDU+' => '',
) );
?>
