<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'FR FR', 'French', 'Français', array (
		'Menu:Electricity' => 'Electricité',
		'Class:Alimentation' => 'Alimentation',
		'Class:Alimentation+' => '',
		//'Class:Alimentation/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerDistributionUnit' => 'Armoire Distribution Elect',
		'Class:PowerDistributionUnit+' => '',
		//'Class:PowerDistributionUnit/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerDistributionUnit/Attribute:powerA_id' => 'Alimentation primaire',
		'Class:PowerDistributionUnit/Attribute:powerA_id+' => 'Tableau Général source',
		'Class:PowerDistributionUnit/Attribute:powerA_name' => 'Nom de l\'alimentation primaire',
		'Class:PowerDistributionUnit/Attribute:powerA_name+' => 'Nom du Tableau Général source',
		'Class:PowerDistributionUnit/Attribute:powerB_id' => 'Alimentation secondaire',
		'Class:PowerDistributionUnit/Attribute:powerB_id+' => 'Alimentation optionnelle',
		'Class:PowerDistributionUnit/Attribute:powerB_name' => 'Alimentation secondaire',
		'Class:PowerDistributionUnit/Attribute:powerB_name+' => 'Alimentation optionnelle',
		'Class:PowerDistributionUnit/Attribute:pdus_list' => 'Liste des PDUs',
		'Class:PowerDistributionUnit/Attribute:pdus_list+' => '',
		'Class:PowerDistributionUnit/Attribute:powerbreakers_list' => 'Liste des disjoncteurs',
		'Class:PowerDistributionUnit/Attribute:powerbreakers_list+' => '',
		'Class:PowerDistributionUnit/Attribute:powercircuits_list' => 'Liste de Circuits Électriques',
		'Class:PowerDistributionUnit/Attribute:powercircuits_list+' => '',
		'Class:PowerDistributionUnit/Attribute:powerfaultdetectionrelays_list' => 'Liste de Différentiels',
		'Class:PowerDistributionUnit/Attribute:powerfaultdetectionrelays_list+' => '',
		'Class:PowerDistributionUnit/Attribute:fqdn' => 'FQDN',
		'Class:PowerDistributionUnit/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PowerDistributionUnit/Attribute:redundancy' => 'Haute disponibilité',
		'Class:PowerDistributionUnit/Attribute:redundancy/disabled' => 'L\'Armoire de distribution est opérationnel si toutes les alimentations qui le composent sont opérationnels',
		'Class:PowerDistributionUnit/Attribute:redundancy/count' => 'Nombre minimal d\'alimentations pour que l\'Armoire de distribution soit opérationnel : %1$s',
		'Class:PowerDistributionUnit/Attribute:redundancy/percent' => 'Pourcentage minimal d\'alimentations pour que l\'Armoire de distribution soit opérationnel : %1$s %%',
		'Class:PowerBreaker' => 'Disjoncteur',
		'Class:PowerBreaker+' => '',
		//'Class:PowerBreaker/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id' => 'Armoire Distribution Elect',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id' => 'Nom de l\'Armoire Distribution Elect',
		'Class:PowerBreaker/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerBreaker/Attribute:pdus_list' => 'Liste des PDUs',
		'Class:PowerBreaker/Attribute:pdus_list+' => '',
		'Class:PowerFaultDetectionRelay' => 'Différenciel',
		'Class:PowerFaultDetectionRelay+' => '',
		//'Class:PowerFaultDetectionRelay/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id' => 'Armoire Distribution Elect',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id' => 'Nom de l\'Armoire Distribution Elect',
		'Class:PowerFaultDetectionRelay/Attribute:powerdistributionunit_id+' => '',
		'Class:PowerFaultDetectionRelay/Attribute:powerbreakers_list' => 'Liste des disjoncteurs',
		'Class:PowerFaultDetectionRelay/Attribute:powerbreakers_list+' => '',
		
		'Class:FootPrint' => 'FootPrint',
		'Class:FootPrint+' => '',
		'Class:FootPrint/Attribute:length' => 'Longueur',
		'Class:FootPrint/Attribute:width' => 'Largeur',
		'Class:FootPrint/Attribute:powercircuits_list' => 'Circuits Électriques',
		'Class:FootPrint/Attribute:powercircuits_list+' => 'Liste des circuits électriques arrivés sous le footprint',
		
		'Class:PowerCircuit' => 'Circuit Électrique',
		'Class:PowerCircuit+' => '',
		'Class:PowerCircuit/Attribute:power_usage' => 'Puissance max (kVA)',
		'Class:PowerCircuit/Attribute:power_usage+' => 'Puissance max du circuit',
		'Class:PowerCircuit/Attribute:type_phase' => 'Type de circuit',
		'Class:PowerCircuit/Attribute:type_phase/Value:monophase' => 'Monophasé',
		'Class:PowerCircuit/Attribute:type_phase/Value:triphase' => 'Triphasé',
		
		'Class:lnkFootPrintToPowerCircuit' => 'LNK FootPrint vers Circuit Électrique',
		'Class:lnkFootPrintToPowerCircuit+' => '',
		'Class:lnkFootPrintToPowerCircuit/Attribute:footprint_id' => 'FootPrint',
		'Class:lnkFootPrintToPowerCircuit/Attribute:powercircuit_id' => 'Circuit Électrique',
		
		'Class:Rack/Attribute:footprint_id' => 'FootPrint',
		'Class:Rack/Attribute:footprint_id+' => 'FootPrint sur lequel est posé le rack',
		'Class:Rack/Attribute:footprint_name' => 'FootPrint',
		
		'Class:PowerGeneralBoard' => 'Armoire TG',
		'Class:PowerGeneralBoard+' => '',
		//'Class:PowerGeneralBoard/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerGeneralBoard/Attribute:fqdn' => 'FQDN',
		'Class:PowerGeneralBoard/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PowerGeneralBoard/Attribute:powersources_list' => 'Liste des alimentations électriques',
		'Class:PowerGeneralBoard/Attribute:powersources_list+' => 'Liste des alimentations électriques',
		'Class:PowerGeneralBoard/Attribute:redundancy' => 'Haute disponibilité',
		'Class:PowerGeneralBoard/Attribute:redundancy/disabled' => 'L\'Armoire TG est opérationnel si toutes les alimentations électriques qui le composent sont opérationnels',
		'Class:PowerGeneralBoard/Attribute:redundancy/count' => 'Nombre minimal d\'alimentations électriques pour que l\'Armoire TG soit opérationnel : %1$s',
		'Class:PowerGeneralBoard/Attribute:redundancy/percent' => 'Pourcentage minimal d\'alimentations électriques pour que l\'Armoire TG soit opérationnel : %1$s %%',
		'Class:Tank' => 'Cuve',
		'Class:Tank+' => '',
		//'Class:Tank/Name' => '%2$s.%3$s - %1$s',
		'Class:Tank/Attribute:groupeelectro_id' => 'Groupe Electrogène',
		'Class:Tank/Attribute:groupeelectro_id+' => '',
		'Class:Tank/Attribute:groupeelectro_name' => 'Nom du Groupe Electrogène',
		'Class:Tank/Attribute:groupeelectro_name+' => '',
		'Class:Tank/Attribute:fqdn' => 'FQDN',
		'Class:Tank/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PowerGenerator' => 'Groupe Electrogène',
		'Class:PowerGenerator+' => '',
		//'Class:PowerGenerator/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerGenerator/Attribute:fqdn' => 'FQDN',
		'Class:PowerGenerator/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PowerSourceInverter' => 'Inverseur de Source',
		'Class:PowerSourceInverter+' => '',
		//'Class:PowerSourceInverter/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerSourceInverter/Attribute:powerA_id' => 'Source électrique A',
		'Class:PowerSourceInverter/Attribute:powerA_id+' => '',
		'Class:PowerSourceInverter/Attribute:powerA_name' => 'Nom Source électrique A',
		'Class:PowerSourceInverter/Attribute:powerA_name+' => '',
		'Class:PowerSourceInverter/Attribute:powerB_id' => 'Source électrique B',
		'Class:PowerSourceInverter/Attribute:powerB_id+' => '',
		'Class:PowerSourceInverter/Attribute:powerB_name' => 'Nom Source électrique B',
		'Class:PowerSourceInverter/Attribute:powerB_name+' => '',
		'Class:PowerSourceInverter/Attribute:redundancy' => 'Redondance',
		'Class:PowerSourceInverter/Attribute:redundancy/count' => 'Le %2$s est alimenté si au moins une source électrique (A ou B) est opérationnelle',
		'Class:PowerSourceInverter/Attribute:toggletype' => 'Méthode de basculement',
		'Class:PowerSourceInverter/Attribute:toggletype/Value:automatic' => 'Automatique',
		'Class:PowerSourceInverter/Attribute:toggletype/Value:manual' => 'Manuelle',
		'Class:UPS' => 'Onduleur',
		'Class:UPS+' => '',
		//'Class:UPS/Name' => '%2$s.%3$s - %1$s',
		'Class:UPS/Attribute:powergeneralboard_list' => 'Armoires TG',
		'Class:UPS/Attribute:powergeneralboard_list+' => 'Liste des Tableaux Généraux connectées',
		'Class:UPS/Attribute:fqdn' => 'FQDN',
		'Class:UPS/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PowerTransform' => 'Transformateur électrique',
		'Class:PowerTransform+' => '',
		//'Class:PowerTransform/Name' => '%2$s.%3$s - %1$s',
		'Class:PowerTransform/Attribute:fqdn' => 'FQDN',
		'Class:PowerTransform/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_id' => 'Source électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_id+' => 'Composant d\'arrivé électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_name' => 'Source électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powersource_name+' => 'Composant d\'arrivé électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_id' => 'Destination électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_id+' => 'Composant utilisant la source électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_name' => 'Destination électrique',
		'Class:lnkPowerSourceToArmoireTG/Attribute:powerconsumer_name+' => 'Composant utilisant la source électriques',
		'Class:PowerSource/Attribute:Transfos_list' => 'PowerTransforms électrique',
		'Class:PowerSource/Attribute:Transfos_list+' => '',
		'Class:PowerConnection/Attribute:facilities_id' => 'Référence Facilities',
		'Class:PowerConnection/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:PowerConnection/Attribute:powerstart_id' => 'Alimentation électrique',
		'Class:PowerConnection/Attribute:powerstart_id+' => '',
		'Class:PowerConnection/Attribute:powerstart_name' => 'Nom de l\'alimentation électrique',
		'Class:PowerConnection/Attribute:powerstart_name+' => '',
		'Class:HVCell' => 'Cellule Haute Tension',
		'Class:HVCell+' => '',
		//'Class:HVCell/Name' => '%2$s.%3$s - %1$s',
		'Class:Battery' => 'Batterie',
		'Class:Battery+' => '',
		//'Class:Battery/Name' => '%2$s.%3$s - %1$s',
		'Class:Battery/Attribute:powerconsumer_id' => 'Composant alimenté',
		'Class:Battery/Attribute:powerconsumer_id+' => '',
		'Class:Battery/Attribute:powerconsumer_name' => 'Nom du composant alimenté',
		'Class:Battery/Attribute:powerconsumer_name+' => '',
		
		'Class:PDU' => 'Bandeau de prises',
		'Class:PDU+' => '',
) );
?>
