<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'EN US', 'English', 'English', array (
		'Class:NetworkInterface/Attribute:org_id' => 'Organization',
		'Class:NetworkInterface/Attribute:org_id+' => '',
		'Class:FiberPanel' => 'Fiber Panel',
		'Class:FiberPanel/Name' => '%1$s - %2$sFO - %3$s - %4$s - %5$s - %6$s',
		'Class:FiberPanel/Attribute:fiber_quantity' => 'Fiber quantity',
		'Class:FiberPanel/Attribute:rearfiberpanel_list' => 'Rear Panel by trunks',
		'Class:FiberPanel/Attribute:frontfiberpanel_list' => 'Front Panel by ports',
		'Class:FiberPanel/Attribute:pdl_list' => 'Deliveries Access Point',
		'Class:FiberPanel/Attribute:customer_id' => 'Panel\'s User',
		'Class:lnkFrontFiberPanels' => 'Link between Front Fiber Panels/Cross-connect',
		'Class:lnkFrontFiberPanels/Name' => '%2$s Port %1$s => %3$s Port %4$s',
		'Class:lnkFrontFiberPanels/Attribute:fiber_quantity' => 'Fiber quantity',
		'Class:lnkFrontFiberPanels/Attribute:fiber_service' => 'Fiber services',
		'Class:lnkFrontFiberPanels/Attribute:source_port' => 'Local Panel fiber ports',
		'Class:lnkFrontFiberPanels/Attribute:firstfiberpanel_id' => 'Local Panel connected',
		'Class:lnkFrontFiberPanels/Attribute:secondfiberpanel_id' => 'Dest Panel connected',
		'Class:lnkFrontFiberPanels/Attribute:secondfiberpanel_id+' => 'Destination Panel where local panel is connected',
		'Class:lnkFrontFiberPanels/Attribute:dest_port' => 'Dest Panel fiber ports',
		'Class:lnkFrontFiberPanels/Attribute:fibermode' => 'Fiber Mode',
		'Class:lnkFrontFiberPanels/Attribute:fibermode/Value:singlemode' => 'Single-Mode',
		'Class:lnkFrontFiberPanels/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:lnkFrontFiberPanels/Attribute:connectortype' => 'Connector Type',
		'Class:lnkRearFiberPanels' => 'Link between Rear Fiber Panels/Trunk',
		'Class:lnkRearFiberPanels/Name' => '%1$s - %2$sFO Pos %3$s => %4$s',
		'Class:lnkRearFiberPanelsAttribute:fiber_quantity' => 'Fiber quantity',
		'Class:lnkRearFiberPanels/Attribute:operator_id' => 'Operator Name',
		'Class:lnkRearFiberPanels/Attribute:firstfiberpanel_id' => 'Local Panel Connected',
		'Class:lnkRearFiberPanels/Attribute:secondfiberpanel_id' => 'Dest Panel Connected',
		'Class:lnkRearFiberPanels/Attribute:secondfiberpanel_id+' => 'Destination Panel where local panel is connected',
		'Class:lnkRearFiberPanels/Attribute:fibermode' => 'Fiber Mode',
		'Class:lnkRearFiberPanels/Attribute:fibermode/Value:singlemode' => 'Single-Mode',
		'Class:lnkRearFiberPanels/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:lnkRearFiberPanels/Attribute:connector_pos' => 'Front Panel connector',
		'Class:FiberRocade' => 'Fiber Rocade',
		'Class:FiberRocade/Name' => '%1$s - %2$sFO',
		'Class:FiberRocade/Attribute:fiber_quantity' => 'Fiber quantity',
		'Class:FiberRocade/Attribute:location_id' => 'Fiber Panel A location',
		'Class:FiberRocade/Attribute:firstfiberpanel_id' => 'Fiber Panel A',
		'Class:FiberRocade/Attribute:location_dest_id' => 'Fiber Panel B location',
		'Class:FiberRocade/Attribute:secondfiberpanel_id' => 'Fiber Panel B',
		'Class:FiberRocade/Attribute:pdl_list' => 'Deliveries Access Point',
		'Class:FiberRocade/Attribute:fibermode' => 'Fiber Mode',
		'Class:FiberRocade/Attribute:fibermode/Value:singlemode' => 'Single-Mode',
		'Class:FiberRocade/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:PDL' => 'Delivery Access Point',
		'Class:PDL/Name' => '%1$s - %2$s - %3$s - %4$s',
		'Class:PDL/Attribute:customer_id' => 'User',
		'Class:PDL/Attribute:fiber_quantity' => 'Fiber quantity',
		'Class:PDL/Attribute:location_id' => 'Fiber Panel location',
		'Class:PDL/Attribute:fiberpaneldevice_id' => 'Fiber Panel',
		'Class:PDL/Attribute:connectortype' => 'Connector Type',
		'Class:PDL/Attribute:fibermode' => 'Fiber Mode',
		'Class:PDL/Attribute:fibermode/Value:singlemode' => 'Single-Mode',
		'Class:PDL/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:PDL/Attribute:rocade_id' => 'Rocade',
		'Class:PDL/Attribute:crossco_id' => 'Cross-Co',
		'Class:CrossCo' => 'Cross-Co',
		'Class:CrossCo/Name' => '%1$s - %2$s - %3$s - %4$s',
		'Class:CrossCo/Attribute:location_id' => 'Location',
		'Class:CrossCo/Attribute:connectortype' => 'Connector Type',
		'Class:CrossCo/Attribute:fibermode' => 'Fiber Mode',
		'Class:CrossCo/Attribute:fibermode/Value:singlemode' => 'Single-Mode',
		'Class:CrossCo/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:CrossCo/Attribute:fibertype' => 'Fibre simplex/duplex',
		'Class:CrossCo/Attribute:fibertype/Value:simplex' => 'Simplex',
		'Class:CrossCo/Attribute:fibertype/Value:duplex' => 'Duplex',
		'Class:CrossCo/Attribute:customer_id' => 'User',
		'Class:CrossCo/Attribute:pdl_list' => 'Deliveries Access Point',
		'Class:CircuitL2' => 'L2 Circuit',
		'Class:CircuitL2/Name' => '%1$s - %2$s',
		'Class:CircuitL2/Attribute:functionalcis_list' => 'CIs',
		'Class:CircuitL2/Attribute:pdl_list' => 'Deliveries Access Point',
		'Class:CircuitL2/Attribute:service_id' => 'Service',
		'Class:CircuitL2/Attribute:speed' => 'Speed',
) );
?>
