<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add('FR FR', 'French', 'Français', array(
		'Class:NetworkInterface/Attribute:org_id' => 'Organisation',
		'Class:NetworkInterface/Attribute:org_id+' => '',
		'Class:FiberPanel' => 'Cassette Fibre',
		'Class:FiberPanel/Name' => '%1$s - %2$sFO - %3$s - %4$s - %5$s - %6$s',
		'Class:FiberPanel/Attribute:fiber_quantity' => 'Nombre de fibre',
		'Class:FiberPanel/Attribute:rearfiberpanel_list' => 'Connecteur arrière / rocade',
		'Class:FiberPanel/Attribute:frontfiberpanel_list' => 'Connecteur avant par ports',
		'Class:FiberPanel/Attribute:pdl_list' => 'Points de livraison',
		'Class:FiberPanel/Attribute:customer_id' => 'Utilisateur cassette',
		'Class:lnkFrontFiberPanels' => 'Liens fibre entre panneau avant / Cross-connect',
		'Class:lnkFrontFiberPanels/Name' => '%2$s Port %1$s => %3$s Port %4$s',
		'Class:lnkFrontFiberPanels/Attribute:fiber_quantity' => 'Nombre de fibre',
		'Class:lnkFrontFiberPanels/Attribute:fiber_service' => 'Service sur la fibre',
		'Class:lnkFrontFiberPanels/Attribute:source_port' => 'Port cassette locale',
		'Class:lnkFrontFiberPanels/Attribute:firstfiberpanel_id' => 'Cassette locale',
		'Class:lnkFrontFiberPanels/Attribute:secondfiberpanel_id' => 'Cassette de destination',
		'Class:lnkFrontFiberPanels/Attribute:secondfiberpanel_id+' => 'Cassette de destination où arrive la fibre',
		'Class:lnkFrontFiberPanels/Attribute:dest_port' => 'Port cassette de destination',
		'Class:lnkFrontFiberPanels/Attribute:fibermode' => 'Type de fibre',
		'Class:lnkFrontFiberPanels/Attribute:fibermode/Value:singlemode' => 'Mono-Mode',
		'Class:lnkFrontFiberPanels/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:lnkFrontFiberPanels/Attribute:connectortype' => 'type de connecteur',
		'Class:lnkRearFiberPanels' => 'Liens fibre entre panneau arrière / Rocade',
		'Class:lnkRearFiberPanels/Name' => '%1$s - %2$sFO Pos %3$s => %4$s',
		'Class:lnkRearFiberPanelsAttribute:fiber_quantity' => 'Nombre de fibre',
		'Class:lnkRearFiberPanels/Attribute:operator_id' => 'Opérateur',
		'Class:lnkRearFiberPanels/Attribute:firstfiberpanel_id' => 'Cassette fibre locale',
		'Class:lnkRearFiberPanels/Attribute:secondfiberpanel_id' => 'Cassette fibre Destination',
		'Class:lnkRearFiberPanels/Attribute:secondfiberpanel_id+' => 'Cassette de destination où arrive la fibre',
		'Class:lnkRearFiberPanels/Attribute:fibermode' => 'Type de fibre',
		'Class:lnkRearFiberPanels/Attribute:fibermode/Value:singlemode' => 'Mono-Mode',
		'Class:lnkRearFiberPanels/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:lnkRearFiberPanels/Attribute:connector_pos' => 'Connecteurs avant correspondant',
		'Class:FiberRocade' => 'Rocade Fibre',
		'Class:FiberRocade/Name' => '%1$s - %2$sFO',
		'Class:FiberRocade/Attribute:fiber_quantity' => 'Nombre de fibre',
		'Class:FiberRocade/Attribute:location_id' => 'Site cassette A',
		'Class:FiberRocade/Attribute:firstfiberpanel_id' => 'Cassette A',
		'Class:FiberRocade/Attribute:location_dest_id' => 'Site cassette B',
		'Class:FiberRocade/Attribute:secondfiberpanel_id' => 'Cassette B',
		'Class:FiberRocade/Attribute:pdl_list' => 'Points de livraison',
		'Class:FiberRocade/Attribute:fibermode' => 'Type de fibre',
		'Class:FiberRocade/Attribute:fibermode/Value:singlemode' => 'Mono-Mode',
		'Class:FiberRocade/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:PDL' => 'Point de livraison',
		'Class:PDL/Name' => '%1$s - %2$s - %3$s - %4$s',
		'Class:PDL/Attribute:fiber_quantity' => 'Nombre de fibre',
		'Class:PDL/Attribute:customer_id' => 'Utilisateur',
		'Class:PDL/Attribute:location_id' => 'Site cassette',
		'Class:PDL/Attribute:fiberpaneldevice_id' => 'Cassette',
		'Class:PDL/Attribute:connectortype' => 'Type de connecteur',
		'Class:PDL/Attribute:fibermode' => 'Type de fibre',
		'Class:PDL/Attribute:fibermode/Value:singlemode' => 'Mono-Mode',
		'Class:PDL/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:PDL/Attribute:rocade_id' => 'Rocade',
		'Class:PDL/Attribute:crossco_id' => 'Cross-Co',
		'Class:CrossCo' => 'Cross-Co',
		'Class:CrossCo/Name' => '%1$s - %2$s - %3$s - %4$s',
		'Class:CrossCo/Attribute:location_id' => 'Site',
		'Class:CrossCo/Attribute:connectortype' => 'Type de connecteur',
		'Class:CrossCo/Attribute:fibermode' => 'Type de fibre',
		'Class:CrossCo/Attribute:fibermode/Value:singlemode' => 'Mono-Mode',
		'Class:CrossCo/Attribute:fibermode/Value:multimode' => 'Multi-Mode',
		'Class:CrossCo/Attribute:fibertype' => 'Fibre simplex/duplex',
		'Class:CrossCo/Attribute:fibertype/Value:simplex' => 'Simplex',
		'Class:CrossCo/Attribute:fibertype/Value:duplex' => 'Duplex',
		'Class:CrossCo/Attribute:customer_id' => 'Utilisateur',
		'Class:CrossCo/Attribute:pdl_list' => 'Points de livraison',
		'Class:CircuitL2' => 'Circuit L2',
		'Class:CircuitL2/Name' => '%1$s - %2$s',
		'Class:CircuitL2/Attribute:functionalcis_list' => 'CIs',
		'Class:CircuitL2/Attribute:pdl_list' => 'Points de livraison',
		'Class:CircuitL2/Attribute:service_id' => 'Service',
		'Class:CircuitL2/Attribute:speed' => 'Vitesse',
));
?>
