<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'EN US', 'English', 'English', array (
		'Menu:Automation' => 'Automation',
		'Class:PhysicalAutomate' => 'Electrical Alimented Object',
		'Class:PhysicalAutomate+' => '',
		//'Class:PhysicalAutomate/Name' => '%2$s - %1$s - %3$s',
		'Class:PhysicalAutomate/Attribute:powerstart_id' => 'Power Alim',
		'Class:PhysicalAutomate/Attribute:powerstart_id+' => '',
		'Class:PhysicalAutomate/Attribute:powerstart_name' => 'Power Alim Name',
		'Class:PhysicalAutomate/Attribute:powerstart_name+' => '',
		'Class:PhysicalAutomate/Attribute:fqdn' => 'FQDN',
		'Class:PhysicalAutomate/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PhysicalAutomate/Attribute:facilities_id' => 'Facilities Reference',
		'Class:PhysicalAutomate/Attribute:facilities_id+' => 'Specific reference for Facilities Team',
		'Class:PowerMeasurment' => 'GTC data collector',
		'Class:PowerMeasurment+' => '',
		//'Class:PowerMeasurment/Name' => '%2$s - %1$s - %3$s',
		'Class:PowerMeasurment/Attribute:softwareinstance_id' => 'GTC Server',
		'Class:PowerMeasurment/Attribute:softwareinstance_id+' => '',
		'Class:PowerMeasurment/Attribute:softwareinstance_name' => 'GTC Server name',
		'Class:PowerMeasurment/Attribute:softwareinstance_name+' => '',
		'Class:PowerMeasurment/Attribute:fqdn' => 'FQDN',
		'Class:PowerMeasurment/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:PowerMeasurment/Attribute:pdu_list' => 'PDU',
		'Class:PowerMeasurment/Attribute:pdu_list+' => 'PDU connected to this GTC Data collector',
		'Class:PDU/Attribute:powermeasurment_id' => 'TDO data collector',
		'Class:PDU/Attribute:powermeasurment_name' => 'TDO data collector Name',
		'Class:PDU/Attribute:oid_tdo' => 'TDO data collector ID',
		'Class:PDU/Attribute:oid_tdo+' => 'ID/final OID for collects electrical data in TDO. Example 10 or 10.2',
		'Class:CCTV' => 'Video camera',
		'Class:CCTV+' => '',
		//'Class:CCTV/Name' => '%2$s - %1$s - %3$s',
		'Class:CCTV/Attribute:cctvrecorder_id' => 'CCTV Recorder',
		'Class:CCTV/Attribute:cctvrecorder_id+' => '',
		'Class:CCTV/Attribute:cctvrecorder_name' => 'CCTV recorder\s name',
		'Class:CCTV/Attribute:cctvrecorder_name+' => '',
		'Class:CCTV/Attribute:fqdn' => 'FQDN',
		'Class:CCTV/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:FirePanel' => 'Fire Panel',
		'Class:FirePanel+' => '',
		//'Class:FirePanel/Name' => '%2$s - %1$s - %3$s',
		'Class:FirePanel/Attribute:firegascylinder_list' => 'Fire Extinguishers',
		'Class:FirePanel/Attribute:firegascylinder_list+' => 'Fire Extinguishers list',
		'Class:FirePanel/Attribute:fqdn' => 'FQDN',
		'Class:FirePanel/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:AlarmPanel' => 'Central alarm',
		'Class:AlarmPanel+' => '',
		//'Class:AlarmPanel/Name' => '%2$s - %1$s - %3$s',
		'Class:AlarmPanel/Attribute:fqdn' => 'FQDN',
		'Class:AlarmPanel/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:AccessControlPanel' => 'Access Controler Box',
		'Class:AccessControlPanel+' => '',
		//'Class:AccessControlPanel/Name' => '%2$s - %1$s - %3$s',
		'Class:AccessControlPanel/Attribute:softwareinstance_id' => 'Winpack server',
		'Class:AccessControlPanel/Attribute:softwareinstance_id+' => '',
		'Class:AccessControlPanel/Attribute:softwareinstance_name' => 'Winpack server name',
		'Class:AccessControlPanel/Attribute:softwareinstance_name+' => '',
		'Class:AccessControlPanel/Attribute:fqdn' => 'FQDN',
		'Class:AccessControlPanel/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:CCTVRecorder' => 'CCTV recoder',
		'Class:CCTVRecorder+' => '',
		//'Class:CCTVRecorder/Name' => '%2$s - %1$s - %3$s',
		'Class:CCTVRecorder/Attribute:softwareinstance_id' => 'IVMS Server',
		'Class:CCTVRecorder/Attribute:softwareinstance_id+' => '',
		'Class:CCTVRecorder/Attribute:softwareinstance_name' => 'IVMS server name',
		'Class:CCTVRecorder/Attribute:softwareinstance_name+' => '',
		'Class:CCTVRecorder/Attribute:cctv_list' => 'Video Cameras',
		'Class:CCTVRecorder/Attribute:cctv_list+' => 'Connected Video Cameras list',
		'Class:CCTVRecorder/Attribute:redundancy' => 'High availability',
		'Class:CCTVRecorder/Attribute:redundancy/disabled' => 'The CCTV recoder is up if all the video cameras are up',
		'Class:CCTVRecorder/Attribute:redundancy/count' => 'The CCTV recoder is up if at least %1$s video camera(s) is(are) up',
		'Class:CCTVRecorder/Attribute:redundancy/percent' => 'The CCTV recoder is up if at least %1$s %% of the video cameras are up',
		'Class:CCTVRecorder/Attribute:fqdn' => 'FQDN',
		'Class:CCTVRecorder/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
		'Class:FireGasCylinder' => 'Fire Extinction',
		'Class:FireGasCylinder+' => '',
		//'Class:FireGasCylinder/Name' => '%2$s - %1$s - %3$s',
		'Class:FireGasCylinder/Attribute:firepanel_id' => 'Fire Panel',
		'Class:FireGasCylinder/Attribute:firepanel_id+' => '',
		'Class:FireGasCylinder/Attribute:firepanel_name' => 'Fire Panel Name',
		'Class:FireGasCylinder/Attribute:firepanel_name+' => '',
		'Class:FireGasCylinder/Attribute:fqdn' => 'FQDN',
		'Class:FireGasCylinder/Attribute:fqdn+' => 'May contain Full Qualified Domain Name or only Domain of the CI',
        'Class:AccessCardReader' => 'Access Card Reader',
        'Class:AccessCardReader+' => '',
        'Class:AccessCardReader/Attribute:coffretcontroleur_id' => 'Access Controler Panel',
        'Class:AccessCardReader/Attribute:coffretcontroleur_id+' => '',
        'Class:AccessCardReader/Attribute:coffretcontroleur_name' => 'Access Controler Panel name',
        'Class:AccessCardReader/Attribute:coffretcontroleur_name+' => '',
        'Class:AccessCardReader/Attribute:digicode' => 'Digicode ?',
        'Class:AccessCardReader/Attribute:digicode+' => '',
        'Class:AccessCardReader/Attribute:digicode/Value:yes' => 'Yes',
        'Class:AccessCardReader/Attribute:digicode/Value:no' => 'No',
        'Class:AccessCardReader/Attribute:biometric' => 'Biometric ?',
        'Class:AccessCardReader/Attribute:biometric+' => '',
        'Class:AccessCardReader/Attribute:biometric/Value:yes' => 'Yes',
        'Class:AccessCardReader/Attribute:biometric/Value:no' => 'No',
        'AccessCardReader:baseinfo' => 'General informations',
        'AccessCardReader:moreinfo' => 'More informations',
        'AccessCardReader:dates' => 'Dates',
) );
?>
