<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
Dict::Add ( 'FR FR', 'French', 'Français', array (
		'Menu:Automation' => 'Automatisme',
		'Class:PhysicalAutomate' => 'Objet d\'automatisme',
		'Class:PhysicalAutomate+' => '',
		//'Class:PhysicalAutomate/Name' => '%2$s - %1$s - %3$s',
		'Class:PhysicalAutomate/Attribute:powerstart_id' => 'Arrivée électrique',
		'Class:PhysicalAutomate/Attribute:powerstart_id+' => '',
		'Class:PhysicalAutomate/Attribute:powerstart_name' => 'Nom Arrivée électrique',
		'Class:PhysicalAutomate/Attribute:powerstart_name+' => '',
		'Class:PhysicalAutomate/Attribute:fqdn' => 'FQDN',
		'Class:PhysicalAutomate/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PhysicalAutomate/Attribute:facilities_id' => 'Référence Facilities',
		'Class:PhysicalAutomate/Attribute:facilities_id+' => 'Réference spécifique à l\'équipe Facilities',
		'Class:PowerMeasurment' => 'Boitier GTC',
		'Class:PowerMeasurment+' => '',
		//'Class:PowerMeasurment/Name' => '%2$s - %1$s - %3$s',
		'Class:PowerMeasurment/Attribute:softwareinstance_id' => 'Serveur GTC',
		'Class:PowerMeasurment/Attribute:softwareinstance_id+' => '',
		'Class:PowerMeasurment/Attribute:softwareinstance_name' => 'Nom du serveur GTC',
		'Class:PowerMeasurment/Attribute:softwareinstance_name+' => '',
		'Class:PowerMeasurment/Attribute:fqdn' => 'FQDN',
		'Class:PowerMeasurment/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:PowerMeasurment/Attribute:pdu_list' => 'PDU',
		'Class:PowerMeasurment/Attribute:pdu_list+' => 'PDU connecté à ce Boitier GTC',
		'Class:PDU/Attribute:powermeasurment_id' => 'Boitier TDO',
		'Class:PDU/Attribute:powermeasurment_name' => 'Nom du Boitier TDO',
		'Class:PDU/Attribute:oid_tdo' => 'ID du TDO à collecter',
		'Class:PDU/Attribute:oid_tdo+' => 'ID ou OID à collecter dans le TDO. Exemple : 10 ou 10.2',
		'Class:CCTV' => 'Caméra Vidéo',
		'Class:CCTV+' => '',
		//'Class:CCTV/Name' => '%2$s - %1$s - %3$s',
		'Class:CCTV/Attribute:cctvrecorder_id' => 'Enregistreur CCTV',
		'Class:CCTV/Attribute:cctvrecorder_id+' => '',
		'Class:CCTV/Attribute:cctvrecorder_name' => 'Nom de l\'Enregistreur CCTV',
		'Class:CCTV/Attribute:cctvrecorder_name+' => '',
		'Class:CCTV/Attribute:fqdn' => 'FQDN',
		'Class:CCTV/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:FirePanel' => 'Centrale Incendie',
		'Class:FirePanel+' => '',
		//'Class:FirePanel/Name' => '%2$s - %1$s - %3$s',
		'Class:FirePanel/Attribute:firegascylinder_list' => 'Extincteurs Incendie',
		'Class:FirePanel/Attribute:firegascylinder_list+' => 'Liste des Extincteurs Incendie connectés',
		'Class:FirePanel/Attribute:fqdn' => 'FQDN',
		'Class:FirePanel/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:AlarmPanel' => 'Centrale d\'Alarme',
		'Class:AlarmPanel+' => '',
		//'Class:AlarmPanel/Name' => '%2$s - %1$s - %3$s',
		'Class:AlarmPanel/Attribute:fqdn' => 'FQDN',
		'Class:AlarmPanel/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:AccessControlPanel' => 'Coffret contrôleur d\'accés',
		'Class:AccessControlPanel+' => '',
		//'Class:AccessControlPanel/Name' => '%2$s - %1$s - %3$s',
		'Class:AccessControlPanel/Attribute:softwareinstance_id' => 'Serveur Winpack',
		'Class:AccessControlPanel/Attribute:softwareinstance_id+' => '',
		'Class:AccessControlPanel/Attribute:softwareinstance_name' => 'Nom du serveur Winpack',
		'Class:AccessControlPanel/Attribute:softwareinstance_name+' => '',
		'Class:AccessControlPanel/Attribute:fqdn' => 'FQDN',
		'Class:AccessControlPanel/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:CCTVRecorder' => 'Enregistreur CCTV',
		'Class:CCTVRecorder+' => '',
		//'Class:CCTVRecorder/Name' => '%2$s - %1$s - %3$s',
		'Class:CCTVRecorder/Attribute:softwareinstance_id' => 'Serveur IVMS',
		'Class:CCTVRecorder/Attribute:softwareinstance_id+' => '',
		'Class:CCTVRecorder/Attribute:softwareinstance_name' => 'Nom du serveur IVMS',
		'Class:CCTVRecorder/Attribute:softwareinstance_name+' => '',
		'Class:CCTVRecorder/Attribute:cctv_list' => 'Caméras Vidéo',
		'Class:CCTVRecorder/Attribute:cctv_list+' => 'Liste des Caméras Vidéo connectées',
		'Class:CCTVRecorder/Attribute:redundancy' => 'Haute disponibilité',
		'Class:CCTVRecorder/Attribute:redundancy/disabled' => 'L\'enregistreur CCTV est opérationnel si toutes les caméras vidéo qui le composent sont opérationnels',
		'Class:CCTVRecorder/Attribute:redundancy/count' => 'Nombre minimal de caméras vidéo pour que l\'enregistreur CCTV soit opérationnel : %1$s',
		'Class:CCTVRecorder/Attribute:redundancy/percent' => 'Pourcentage minimal de caméras vidéo pour que l\'enregistreur CCTV soit opérationnel : %1$s %%',
		'Class:CCTVRecorder/Attribute:fqdn' => 'FQDN',
		'Class:CCTVRecorder/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
		'Class:FireGasCylinder' => 'Extinction d\'Incendie',
		'Class:FireGasCylinder+' => '',
		//'Class:FireGasCylinder/Name' => '%2$s - %1$s - %3$s',
		'Class:FireGasCylinder/Attribute:firepanel_id' => 'Centrale Incendie',
		'Class:FireGasCylinder/Attribute:firepanel_id+' => '',
		'Class:FireGasCylinder/Attribute:firepanel_name' => 'Nom de la Centrale Incendie',
		'Class:FireGasCylinder/Attribute:firepanel_name+' => '',
		'Class:FireGasCylinder/Attribute:fqdn' => 'FQDN',
		'Class:FireGasCylinder/Attribute:fqdn+' => 'Peut contenir le Full Qualified Domain Name ou seulement le Domaine du CI',
        'Class:AccessCardReader' => 'Lecteur de carte',
        'Class:AccessCardReader+' => '',
        'Class:AccessCardReader/Attribute:coffretcontroleur_id' => 'Boitier contrôleur d\'accès',
        'Class:AccessCardReader/Attribute:coffretcontroleur_id+' => '',
        'Class:AccessCardReader/Attribute:coffretcontroleur_name' => 'Boitier contrôleur d\'accès',
        'Class:AccessCardReader/Attribute:coffretcontroleur_name+' => '',
        'Class:AccessCardReader/Attribute:digicode' => 'Digicode ?',
        'Class:AccessCardReader/Attribute:digicode+' => '',
        'Class:AccessCardReader/Attribute:digicode/Value:yes' => 'Yes',
        'Class:AccessCardReader/Attribute:digicode/Value:no' => 'No',
        'Class:AccessCardReader/Attribute:biometric' => 'Biométrique ?',
        'Class:AccessCardReader/Attribute:biometric+' => '',
        'Class:AccessCardReader/Attribute:biometric/Value:yes' => 'Yes',
        'Class:AccessCardReader/Attribute:biometric/Value:no' => 'No',
        'AccessCardReader:baseinfo' => 'Informations Générales',
        'AccessCardReader:moreinfo' => 'Informations supplémentaires',
        'AccessCardReader:dates' => 'Dates',
) );
?>
